######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:54:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . \
               ../../../lib/database/include/ \
               ../../../lib/interaction/include/ \
               ../../../lib/nodekits/include/

# Input
SOURCES += ivcat.cpp
