DEPENDPATH += database \
              database/include \
              database/include/Inventor \
              database/include/Inventor/actions \
              database/include/Inventor/bundles \
              database/include/Inventor/caches \
              database/include/Inventor/details \
              database/include/Inventor/elements \
              database/include/Inventor/engines \
              database/include/Inventor/errors \
              database/include/Inventor/events \
              database/include/Inventor/fields \
              database/include/Inventor/misc \
              database/include/Inventor/nodes \
              database/include/Inventor/projectors \
              database/include/Inventor/sensors \
              database/include/Inventor/threads \
              database/include/Inventor/misc/upgraders \
              database/src/projectors \
              database/src/actions \
              database/src/bundles \
              database/src/caches \
              database/src/details \
              database/src/elements \
              database/src/engines \
              database/src/errors \
              database/src/events \
              database/src/fields \
              database/src/nodes \
              database/src/sensors \
              database/src/upgraders

INCLUDEPATH += database/src/engines \
               database/src/opengl \
               database/include/Inventor/misc


PUBLIC_HEADERS += database/include/machine.h \
           database/include/SoDebug.h \
           database/include/SoUnknownEngine.h \
           database/include/SoUnknownNode.h \
           database/include/Inventor/Sb.h \
           database/include/Inventor/SbBasic.h \
           database/include/Inventor/SbBox.h \
           database/include/Inventor/SbBox3f.h \
           database/include/Inventor/SbXfBox3f.h \
           database/include/Inventor/SbBox2f.h \
           database/include/Inventor/SbBox2s.h \
           database/include/Inventor/SbColor.h \
           database/include/Inventor/SbDict.h \
           database/include/Inventor/SbFile.h \
           database/include/Inventor/SbImage.h \
           database/include/Inventor/SbStdint.h \
           database/include/Inventor/SbLinear.h \
           database/include/Inventor/SbName.h \
           database/include/Inventor/SbNameEntry.h \
           database/include/Inventor/SbVec2f.h \
           database/include/Inventor/SbVec2s.h \
           database/include/Inventor/SbVec2i32.h \
           database/include/Inventor/SbVec3s.h \
           database/include/Inventor/SbVec3f.h \
           database/include/Inventor/SbVec3i32.h \
           database/include/Inventor/SbVec3d.h \
           database/include/Inventor/SbVec4f.h \
           database/include/Inventor/SbVec4d.h \
           database/include/Inventor/SbVec4i32.h \
           database/include/Inventor/SbMatrix.h \
           database/include/Inventor/SbMatrixd.h \
           database/include/Inventor/SbRefPtr.h \
           database/include/Inventor/SbRotation.h \
           database/include/Inventor/SbRotationd.h \
           database/include/Inventor/SbLine.h \
           database/include/Inventor/SbPlane.h \
           database/include/Inventor/SbSphere.h \
           database/include/Inventor/SbCylinder.h \
           database/include/Inventor/SbViewVolume.h \
           database/include/Inventor/SbPList.h \
           database/include/Inventor/SbString.h \
           database/include/Inventor/SbTime.h \
           database/include/Inventor/SbViewportRegion.h \
           database/include/Inventor/So.h \
           database/include/Inventor/SoDB.h \
           database/include/Inventor/SoInput.h \
           database/include/Inventor/SoLists.h \
           database/include/Inventor/SoOffscreenRenderer.h \
           database/include/Inventor/SoOutput.h \
           database/include/Inventor/SoPath.h \
           database/include/Inventor/SoFullPath.h \
           database/include/Inventor/SoLightPath.h \
           database/include/Inventor/SoPickedPoint.h \
           database/include/Inventor/SoPrimitiveVertex.h \
           database/include/Inventor/SoType.h \
           database/include/Inventor/actions/SoAction.h \
           database/include/Inventor/actions/SoActionMethodList.h \
           database/include/Inventor/actions/SoEnabledElementsList.h \
           database/include/Inventor/actions/SoActions.h \
           database/include/Inventor/actions/SoCallbackAction.h \
           database/include/Inventor/actions/SoGetBoundingBoxAction.h \
           database/include/Inventor/actions/SoGetMatrixAction.h \
           database/include/Inventor/actions/SoGLRenderAction.h \
           database/include/Inventor/actions/SoHandleEventAction.h \
           database/include/Inventor/actions/SoPickAction.h \
           database/include/Inventor/actions/SoRayPickAction.h \
           database/include/Inventor/actions/SoSearchAction.h \
           database/include/Inventor/actions/SoSubAction.h \
           database/include/Inventor/actions/SoWriteAction.h \
           database/include/Inventor/bundles/SoBundle.h \
           database/include/Inventor/bundles/SoMaterialBundle.h \
           database/include/Inventor/bundles/SoNormalBundle.h \
           database/include/Inventor/bundles/SoTextureCoordinateBundle.h \
           database/include/Inventor/caches/SoBoundingBoxCache.h \
           database/include/Inventor/caches/SoCache.h \
           database/include/Inventor/caches/SoGLCacheList.h \
           database/include/Inventor/caches/SoGLDisplayList.h \
           database/include/Inventor/caches/SoGLRenderCache.h \
           database/include/Inventor/caches/SoNormalCache.h \
           database/include/Inventor/caches/SoVertexPropertyCache.h \
           database/include/Inventor/details/SoConeDetail.h \
           database/include/Inventor/details/SoCubeDetail.h \
           database/include/Inventor/details/SoCylinderDetail.h \
           database/include/Inventor/details/SoDetail.h \
           database/include/Inventor/details/SoDetails.h \
           database/include/Inventor/details/SoFaceDetail.h \
           database/include/Inventor/details/SoLineDetail.h \
           database/include/Inventor/details/SoPointDetail.h \
           database/include/Inventor/details/SoSubDetail.h \
           database/include/Inventor/details/SoTextDetail.h \
           database/include/Inventor/elements/SoAccumulatedElement.h \
           database/include/Inventor/elements/SoBBoxModelMatrixElement.h \
           database/include/Inventor/elements/SoCacheElement.h \
           database/include/Inventor/elements/SoClipPlaneElement.h \
           database/include/Inventor/elements/SoComplexityElement.h \
           database/include/Inventor/elements/SoComplexityTypeElement.h \
           database/include/Inventor/elements/SoCoordinateElement.h \
           database/include/Inventor/elements/SoCreaseAngleElement.h \
           database/include/Inventor/elements/SoDepthBufferElement.h \
           database/include/Inventor/elements/SoGLDepthBufferElement.h \
           database/include/Inventor/elements/SoDrawStyleElement.h \
           database/include/Inventor/elements/SoElement.h \
           database/include/Inventor/elements/SoElements.h \
           database/include/Inventor/elements/SoFloatElement.h \
           database/include/Inventor/elements/SoFocalDistanceElement.h \
           database/include/Inventor/elements/SoFontNameElement.h \
           database/include/Inventor/elements/SoFontSizeElement.h \
           database/include/Inventor/elements/SoGLCacheContextElement.h \
           database/include/Inventor/elements/SoGLClipPlaneElement.h \
           database/include/Inventor/elements/SoGLCoordinateElement.h \
           database/include/Inventor/elements/SoGLDrawStyleElement.h \
           database/include/Inventor/elements/SoGLLazyElement.h \
           database/include/Inventor/elements/SoGLLightIdElement.h \
           database/include/Inventor/elements/SoGLLinePatternElement.h \
           database/include/Inventor/elements/SoGLLineWidthElement.h \
           database/include/Inventor/elements/SoGLModelMatrixElement.h \
           database/include/Inventor/elements/SoGLNormalElement.h \
           database/include/Inventor/elements/SoGLPointSizeElement.h \
           database/include/Inventor/elements/SoGLPolygonOffsetElement.h \
           database/include/Inventor/elements/SoGLProjectionMatrixElement.h \
           database/include/Inventor/elements/SoGLRenderPassElement.h \
           database/include/Inventor/elements/SoGLShapeHintsElement.h \
           database/include/Inventor/elements/SoGLTextureCoordinateElement.h \
           database/include/Inventor/elements/SoGLTextureEnabledElement.h \
           database/include/Inventor/elements/SoGLTextureImageElement.h \
           database/include/Inventor/elements/SoGLTextureMatrixElement.h \
           database/include/Inventor/elements/SoGLTextureCoordinate3Element.h \
           database/include/Inventor/elements/SoGLTextureUnitElement.h \
           database/include/Inventor/elements/SoGLUpdateAreaElement.h \
           database/include/Inventor/elements/SoGLViewingMatrixElement.h \
           database/include/Inventor/elements/SoGLViewportRegionElement.h \
           database/include/Inventor/elements/SoInt32Element.h \
           database/include/Inventor/elements/SoLazyElement.h \
           database/include/Inventor/elements/SoLightAttenuationElement.h \
           database/include/Inventor/elements/SoLinePatternElement.h \
           database/include/Inventor/elements/SoLineWidthElement.h \
           database/include/Inventor/elements/SoLocalBBoxMatrixElement.h \
           database/include/Inventor/elements/SoMaterialBindingElement.h \
           database/include/Inventor/elements/SoModelMatrixElement.h \
           database/include/Inventor/elements/SoNormalBindingElement.h \
           database/include/Inventor/elements/SoNormalElement.h \
           database/include/Inventor/elements/SoOverrideElement.h \
           database/include/Inventor/elements/SoPickRayElement.h \
           database/include/Inventor/elements/SoPickStyleElement.h \
           database/include/Inventor/elements/SoPointSizeElement.h \
           database/include/Inventor/elements/SoPolygonOffsetElement.h \
           database/include/Inventor/elements/SoProfileCoordinateElement.h \
           database/include/Inventor/elements/SoProfileElement.h \
           database/include/Inventor/elements/SoProjectionMatrixElement.h \
           database/include/Inventor/elements/SoReplacedElement.h \
           database/include/Inventor/elements/SoShapeHintsElement.h \
           database/include/Inventor/elements/SoShapeStyleElement.h \
           database/include/Inventor/elements/SoSpecularColorElement.h \
           database/include/Inventor/elements/SoSubElement.h \
           database/include/Inventor/elements/SoStereoElement.h \
           database/include/Inventor/elements/SoSwitchElement.h \
           database/include/Inventor/elements/SoTextureCoordinateBindingElement.h \
           database/include/Inventor/elements/SoTextureCoordinateElement.h \
           database/include/Inventor/elements/SoTextureImageElement.h \
           database/include/Inventor/elements/SoTextureMatrixElement.h \
           database/include/Inventor/elements/SoTextureQualityElement.h \
           database/include/Inventor/elements/SoTextureCoordinate3Element.h \
           database/include/Inventor/elements/SoTextureUnitElement.h \
           database/include/Inventor/elements/SoTransparencyTypeElement.h \
           database/include/Inventor/elements/SoUnitsElement.h \
           database/include/Inventor/elements/SoViewingMatrixElement.h \
           database/include/Inventor/elements/SoViewportRegionElement.h \
           database/include/Inventor/elements/SoViewVolumeElement.h \
           database/include/Inventor/engines/SoBoolOperation.h \
           database/include/Inventor/engines/SoCalculator.h \
           database/include/Inventor/engines/SoCompose.h \
           database/include/Inventor/engines/SoComputeBoundingBox.h \
           database/include/Inventor/engines/SoConcatenate.h \
           database/include/Inventor/engines/SoCounter.h \
           database/include/Inventor/engines/SoElapsedTime.h \
           database/include/Inventor/engines/SoEngine.h \
           database/include/Inventor/engines/SoEngineOutput.h \
           database/include/Inventor/engines/SoEngines.h \
           database/include/Inventor/engines/SoFieldConverter.h \
           database/include/Inventor/engines/SoGate.h \
           database/include/Inventor/engines/SoInterpolate.h \
           database/include/Inventor/engines/SoOneShot.h \
           database/include/Inventor/engines/SoOnOff.h \
           database/include/Inventor/engines/SoOutputData.h \
           database/include/Inventor/engines/SoSelectOne.h \
           database/include/Inventor/engines/SoSubEngine.h \
           database/include/Inventor/engines/SoTimeCounter.h \
           database/include/Inventor/engines/SoTransformVec3f.h \
           database/include/Inventor/engines/SoTriggerAny.h \
           database/include/Inventor/errors/SoDebugError.h \
           database/include/Inventor/errors/SoError.h \
           database/include/Inventor/errors/SoErrors.h \
           database/include/Inventor/errors/SoMemoryError.h \
           database/include/Inventor/errors/SoReadError.h \
           database/include/Inventor/events/SoButtonEvent.h \
           database/include/Inventor/events/SoEvent.h \
           database/include/Inventor/events/SoEvents.h \
           database/include/Inventor/events/SoKeyboardEvent.h \
           database/include/Inventor/events/SoLocation2Event.h \
           database/include/Inventor/events/SoMotion3Event.h \
           database/include/Inventor/events/SoMouseButtonEvent.h \
           database/include/Inventor/events/SoSpaceballButtonEvent.h \
           database/include/Inventor/events/SoSubEvent.h \
           database/include/Inventor/events/SbTrackerInfo.h \
           database/include/Inventor/events/SoControllerButtonEvent.h \
           database/include/Inventor/events/SoTrackerEvent.h \
           database/include/Inventor/fields/SoField.h \
           database/include/Inventor/fields/SoSField.h \
           database/include/Inventor/fields/SoMField.h \
           database/include/Inventor/fields/SoFieldContainer.h \
           database/include/Inventor/fields/SoFieldData.h \
           database/include/Inventor/fields/SoFields.h \
           database/include/Inventor/fields/SoMFBitMask.h \
           database/include/Inventor/fields/SoMFBool.h \
           database/include/Inventor/fields/SoMFColor.h \
           database/include/Inventor/fields/SoMFEngine.h \
           database/include/Inventor/fields/SoMFEnum.h \
           database/include/Inventor/fields/SoMFFloat.h \
           database/include/Inventor/fields/SoMFInt32.h \
           database/include/Inventor/fields/SoMFMatrix.h \
           database/include/Inventor/fields/SoMFName.h \
           database/include/Inventor/fields/SoMFNode.h \
           database/include/Inventor/fields/SoMFPath.h \
           database/include/Inventor/fields/SoMFPlane.h \
           database/include/Inventor/fields/SoMFRotation.h \
           database/include/Inventor/fields/SoMFShort.h \
           database/include/Inventor/fields/SoMFString.h \
           database/include/Inventor/fields/SoMFTime.h \
           database/include/Inventor/fields/SoMFUInt32.h \
           database/include/Inventor/fields/SoMFUShort.h \
           database/include/Inventor/fields/SoMFVec2f.h \
           database/include/Inventor/fields/SoMFVec3f.h \
           database/include/Inventor/fields/SoMFVec3i32.h \
           database/include/Inventor/fields/SoMFVec4f.h \
           database/include/Inventor/fields/SoMFVec4i32.h \
           database/include/Inventor/fields/SoSFBitMask.h \
           database/include/Inventor/fields/SoSFBool.h \
           database/include/Inventor/fields/SoSFBox3f.h \
           database/include/Inventor/fields/SoSFColor.h \
           database/include/Inventor/fields/SoSFEngine.h \
           database/include/Inventor/fields/SoSFEnum.h \
           database/include/Inventor/fields/SoSFFloat.h \
           database/include/Inventor/fields/SoSFImage.h \
           database/include/Inventor/fields/SoSFInt32.h \
           database/include/Inventor/fields/SoSFMatrix.h \
           database/include/Inventor/fields/SoSFName.h \
           database/include/Inventor/fields/SoSFNode.h \
           database/include/Inventor/fields/SoSFPath.h \
           database/include/Inventor/fields/SoSFPlane.h \
           database/include/Inventor/fields/SoSFRotation.h \
           database/include/Inventor/fields/SoSFShort.h \
           database/include/Inventor/fields/SoSFString.h \
           database/include/Inventor/fields/SoSFTime.h \
           database/include/Inventor/fields/SoSFTrigger.h \
           database/include/Inventor/fields/SoSFUInt32.h \
           database/include/Inventor/fields/SoSFUShort.h \
           database/include/Inventor/fields/SoSFVec2f.h \
           database/include/Inventor/fields/SoSFVec3f.h \
           database/include/Inventor/fields/SoSFVec4f.h \
           database/include/Inventor/fields/SoSubField.h \
           database/include/Inventor/lists/SbIntList.h \
           database/include/Inventor/lists/SbVec3fList.h \
           database/include/Inventor/lists/SbStringList.h \
           database/include/Inventor/lists/SoBaseList.h \
           database/include/Inventor/lists/SoNodeList.h \
           database/include/Inventor/lists/SoPathList.h \
           database/include/Inventor/lists/SoEngineList.h \
           database/include/Inventor/lists/SoTypeList.h \
           database/include/Inventor/lists/SoDetailList.h \
           database/include/Inventor/lists/SoPickedPointList.h \
           database/include/Inventor/lists/SoFieldList.h \
           database/include/Inventor/lists/SoEngineOutputList.h \
           database/include/Inventor/lists/SoAuditorList.h \
           database/include/Inventor/misc/SoAuditorList.h \
           database/include/Inventor/misc/SoBase.h \
           database/include/Inventor/misc/SoBasic.h \
           database/include/Inventor/misc/SoByteStream.h \
           database/include/Inventor/misc/SoCallbackList.h \
           database/include/Inventor/misc/SoChildList.h \
           database/include/Inventor/misc/SoCompactPathList.h \
           database/include/Inventor/misc/SoGL.h \
           database/include/Inventor/misc/SoGLContext.h \
           database/include/Inventor/misc/SoNormalGenerator.h \
           database/include/Inventor/misc/SoNotification.h \
           database/include/Inventor/misc/SoState.h \
           database/include/Inventor/misc/SoTempPath.h \
           database/include/Inventor/misc/SoTranscribe.h \
           database/include/Inventor/nodes/SoAnnotation.h \
           database/include/Inventor/nodes/SoArray.h \
           database/include/Inventor/nodes/SoAsciiText.h \
           database/include/Inventor/nodes/SoBaseColor.h \
           database/include/Inventor/nodes/SoBlinker.h \
           database/include/Inventor/nodes/SoCallback.h \
           database/include/Inventor/nodes/SoCamera.h \
           database/include/Inventor/nodes/SoClipPlane.h \
           database/include/Inventor/nodes/SoColorIndex.h \
           database/include/Inventor/nodes/SoComplexity.h \
           database/include/Inventor/nodes/SoCone.h \
           database/include/Inventor/nodes/SoCoordinate3.h \
           database/include/Inventor/nodes/SoCoordinate4.h \
           database/include/Inventor/nodes/SoCube.h \
           database/include/Inventor/nodes/SoCylinder.h \
           database/include/Inventor/nodes/SoDepthBuffer.h \
           database/include/Inventor/nodes/SoDirectionalLight.h \
           database/include/Inventor/nodes/SoDrawStyle.h \
           database/include/Inventor/nodes/SoEnvironment.h \
           database/include/Inventor/nodes/SoEventCallback.h \
           database/include/Inventor/nodes/SoFaceSet.h \
           database/include/Inventor/nodes/SoFile.h \
           database/include/Inventor/nodes/SoFont.h \
           database/include/Inventor/nodes/SoFontStyle.h \
           database/include/Inventor/nodes/SoGroup.h \
           database/include/Inventor/nodes/SoIndexedFaceSet.h \
           database/include/Inventor/nodes/SoIndexedLineSet.h \
           database/include/Inventor/nodes/SoIndexedNurbsCurve.h \
           database/include/Inventor/nodes/SoIndexedNurbsSurface.h \
           database/include/Inventor/nodes/SoIndexedPointSet.h \
           database/include/Inventor/nodes/SoIndexedShape.h \
           database/include/Inventor/nodes/SoIndexedTriangleStripSet.h \
           database/include/Inventor/nodes/SoInfo.h \
           database/include/Inventor/nodes/SoLabel.h \
           database/include/Inventor/nodes/SoLevelOfDetail.h \
           database/include/Inventor/nodes/SoLight.h \
           database/include/Inventor/nodes/SoLightModel.h \
           database/include/Inventor/nodes/SoLinearProfile.h \
           database/include/Inventor/nodes/SoLineSet.h \
           database/include/Inventor/nodes/SoLocateHighlight.h \
           database/include/Inventor/nodes/SoLOD.h \
           database/include/Inventor/nodes/SoMaterial.h \
           database/include/Inventor/nodes/SoMaterialBinding.h \
           database/include/Inventor/nodes/SoMatrixTransform.h \
           database/include/Inventor/nodes/SoMultipleCopy.h \
           database/include/Inventor/nodes/SoNode.h \
           database/include/Inventor/nodes/SoNodes.h \
           database/include/Inventor/nodes/SoNonIndexedShape.h \
           database/include/Inventor/nodes/SoNormal.h \
           database/include/Inventor/nodes/SoNormalBinding.h \
           database/include/Inventor/nodes/SoNurbsCurve.h \
           database/include/Inventor/nodes/SoNurbsProfile.h \
           database/include/Inventor/nodes/SoNurbsSurface.h \
           database/include/Inventor/nodes/SoOrthographicCamera.h \
           database/include/Inventor/nodes/SoPackedColor.h \
           database/include/Inventor/nodes/SoPathSwitch.h \
           database/include/Inventor/nodes/SoPendulum.h \
           database/include/Inventor/nodes/SoPerspectiveCamera.h \
           database/include/Inventor/nodes/SoPickStyle.h \
           database/include/Inventor/nodes/SoPointLight.h \
           database/include/Inventor/nodes/SoPointSet.h \
           database/include/Inventor/nodes/SoPolygonOffset.h \
           database/include/Inventor/nodes/SoProfile.h \
           database/include/Inventor/nodes/SoProfileCoordinate2.h \
           database/include/Inventor/nodes/SoProfileCoordinate3.h \
           database/include/Inventor/nodes/SoQuadMesh.h \
           database/include/Inventor/nodes/SoResetTransform.h \
           database/include/Inventor/nodes/SoRotation.h \
           database/include/Inventor/nodes/SoRotationXYZ.h \
           database/include/Inventor/nodes/SoRotor.h \
           database/include/Inventor/nodes/SoScale.h \
           database/include/Inventor/nodes/SoSeparator.h \
           database/include/Inventor/nodes/SoShape.h \
           database/include/Inventor/nodes/SoShapeHints.h \
           database/include/Inventor/nodes/SoShuttle.h \
           database/include/Inventor/nodes/SoSphere.h \
           database/include/Inventor/nodes/SoSpotLight.h \
           database/include/Inventor/nodes/SoSubNode.h \
           database/include/Inventor/nodes/SoSwitch.h \
           database/include/Inventor/nodes/SoText2.h \
           database/include/Inventor/nodes/SoText3.h \
           database/include/Inventor/nodes/SoTexture2.h \
           database/include/Inventor/nodes/SoTexture2Transform.h \
           database/include/Inventor/nodes/SoTextureCoordinate2.h \
           database/include/Inventor/nodes/SoTextureCoordinateBinding.h \
           database/include/Inventor/nodes/SoTextureCoordinateDefault.h \
           database/include/Inventor/nodes/SoTextureCoordinateEnvironment.h \
           database/include/Inventor/nodes/SoTextureCoordinateFunction.h \
           database/include/Inventor/nodes/SoTextureCoordinateObject.h \
           database/include/Inventor/nodes/SoTextureCoordinatePlane.h \
           database/include/Inventor/nodes/SoTextureCoordinate3.h \
           database/include/Inventor/nodes/SoTextureUnit.h \
           database/include/Inventor/nodes/SoTransform.h \
           database/include/Inventor/nodes/SoTransformation.h \
           database/include/Inventor/nodes/SoTransformSeparator.h \
           database/include/Inventor/nodes/SoTranslation.h \
           database/include/Inventor/nodes/SoTransparencyType.h \
           database/include/Inventor/nodes/SoTriangleStripSet.h \
           database/include/Inventor/nodes/SoUnits.h \
           database/include/Inventor/nodes/SoVertexProperty.h \
           database/include/Inventor/nodes/SoVertexShape.h \
           database/include/Inventor/nodes/SoWWWAnchor.h \
           database/include/Inventor/nodes/SoWWWInline.h \
           database/include/Inventor/projectors/SbCylinderPlaneProjector.h \
           database/include/Inventor/projectors/SbCylinderProjector.h \
           database/include/Inventor/projectors/SbCylinderSectionProjector.h \
           database/include/Inventor/projectors/SbCylinderSheetProjector.h \
           database/include/Inventor/projectors/SbLineProjector.h \
           database/include/Inventor/projectors/SbPlaneProjector.h \
           database/include/Inventor/projectors/SbProjector.h \
           database/include/Inventor/projectors/SbProjectors.h \
           database/include/Inventor/projectors/SbSpherePlaneProjector.h \
           database/include/Inventor/projectors/SbSphereProjector.h \
           database/include/Inventor/projectors/SbSphereSectionProjector.h \
           database/include/Inventor/projectors/SbSphereSheetProjector.h \
           database/include/Inventor/sensors/SoAlarmSensor.h \
           database/include/Inventor/sensors/SoDataSensor.h \
           database/include/Inventor/sensors/SoDelayQueueSensor.h \
           database/include/Inventor/sensors/SoFieldSensor.h \
           database/include/Inventor/sensors/SoIdleSensor.h \
           database/include/Inventor/sensors/SoNodeSensor.h \
           database/include/Inventor/sensors/SoOneShotSensor.h \
           database/include/Inventor/sensors/SoPathSensor.h \
           database/include/Inventor/sensors/SoSensor.h \
           database/include/Inventor/sensors/SoSensorManager.h \
           database/include/Inventor/sensors/SoSensors.h \
           database/include/Inventor/sensors/SoTimerQueueSensor.h \
           database/include/Inventor/sensors/SoTimerSensor.h \
           database/include/Inventor/threads/SbThreadAutoLock.h \
           database/include/Inventor/threads/SbThreadMutex.h \
           database/include/Inventor/misc/upgraders/SoUpgrader.h \
           database/include/Inventor/misc/upgraders/SoV1CustomNode.h

PRIVATE_HEADERS += database/include/Inventor/caches/SoBitmapFontCache.h \
           database/include/Inventor/caches/SoOutlineFontCache.h \
           database/include/Inventor/caches/SoFontOutline.h \
           database/src/engines/SoCalcExpr.h \
           database/src/engines/SoEngineUtil.h \
           database/src/engines/SoFieldConverters.h \
           database/src/fields/SoGlobalField.h \
           database/src/opengl/SbGLContext.h \
           database/src/opengl/SbGLFramebufferObject.h \
           database/src/upgraders/SoUpgraders.h \
           database/src/upgraders/SoV1DrawStyle.h \
           database/src/upgraders/SoV1Environment.h \
           database/src/upgraders/SoV1IndexedTriangleMesh.h \
           database/src/upgraders/SoV1LayerGroup.h \
           database/src/upgraders/SoV1LightModel.h \
           database/src/upgraders/SoV1Material.h \
           database/src/upgraders/SoV1PackedColor.h \
           database/src/upgraders/SoV1PickStyle.h \
           database/src/upgraders/SoV1Separator.h \
           database/src/upgraders/SoV1ShapeHints.h \
           database/src/upgraders/SoV1Text2.h \
           database/src/upgraders/SoV1Text3.h \
           database/src/upgraders/SoV1Texture2.h \
           database/src/upgraders/SoV1TextureCoordinateCube.h \
           database/src/upgraders/SoV1TextureCoordinateCylinder.h \
           database/src/upgraders/SoV1TextureCoordinateEnvironment.h \
           database/src/upgraders/SoV1TextureCoordinatePlane.h \
           database/src/upgraders/SoV1TextureCoordinateSphere.h \
           database/src/upgraders/SoV2AsciiText.h \
           database/src/upgraders/SoV2FontStyle.h \
           database/src/upgraders/SoV2LOD.h \
           database/src/upgraders/SoV2MaterialIndex.h \
           database/src/upgraders/SoV2Text2.h \
           database/src/upgraders/SoV2Text3.h \
           database/src/upgraders/SoV2VertexProperty.h \
           database/src/upgraders/SoV2WWWAnchor.h \
           database/src/upgraders/SoV2WWWInline.h

HEADERS += $$PUBLIC_HEADERS $$PRIVATE_HEADERS

YACCSOURCES += database/src/engines/SoCalcParse.y

SOURCES += database/src/SbBox3f.cpp \
           database/src/SbXfBox3f.cpp \
           database/src/SbBox2f.cpp \
           database/src/SbBox2s.cpp \
           database/src/SbColor.cpp \
           database/src/SbCylinder.cpp \
           database/src/SbDict.cpp \
           database/src/SbFile.cpp \
           database/src/SbImage.cpp \
           database/src/SbLine.cpp \
           database/src/SbMatrix.cpp \
           database/src/SbMatrixd.cpp \
           database/src/SbName.cpp \
           database/src/SbNameEntry.cpp \
           database/src/SbPlane.cpp \
           database/src/SbRotation.cpp \
           database/src/SbRotationd.cpp \
           database/src/SbSphere.cpp \
           database/src/SbString.cpp \
           database/src/SbTime.cpp \
           database/src/SbVec2f.cpp \
           database/src/SbVec2s.cpp \
           database/src/SbVec2i32.cpp \
           database/src/SbVec3s.cpp \
           database/src/SbVec3f.cpp \
           database/src/SbVec3i32.cpp \
           database/src/SbVec3d.cpp \
           database/src/SbVec4f.cpp \
           database/src/SbVec4d.cpp \
           database/src/SbVec4i32.cpp \
           database/src/SbViewVolume.cpp \
           database/src/SbViewportRegion.cpp \
           database/src/lists/SbPList.cpp \
           database/src/lists/SbVec3fList.cpp \
           database/src/lists/SoAuditorList.cpp \
           database/src/lists/SoBaseList.cpp \
           database/src/lists/SoDetailList.cpp \
           database/src/lists/SoPathList.cpp \
           database/src/lists/SoPickedPointList.cpp \
           database/src/lists/SoTypeList.cpp \
           database/src/SoBase.cpp \
           database/src/SoByteStream.cpp \
           database/src/SoCallbackList.cpp \
           database/src/SoChildList.cpp \
           database/src/SoCompactPathList.cpp \
           database/src/SoDB.cpp \
           database/src/SoDebug.cpp \
           database/src/SoInput.cpp \
           database/src/SoNormalGenerator.cpp \
           database/src/SoNotification.cpp \
           database/src/SoOffscreenRenderer.cpp \
           database/src/SoOutput.cpp \
           database/src/SoPath.cpp \
           database/src/SoFullPath.cpp \
           database/src/SoLightPath.cpp \
           database/src/SoPickedPoint.cpp \
           database/src/SoPrimitiveVertex.cpp \
           database/src/SoState.cpp \
           database/src/SoTempPath.cpp \
           database/src/SoTranscribe.cpp \
           database/src/SoType.cpp \
           database/src/opengl/SbGLContext.cpp \
           database/src/opengl/SbGLFramebufferObject.cpp \
           database/src/projectors/SbCylinderPlaneProjector.cpp \
           database/src/projectors/SbCylinderProjector.cpp \
           database/src/projectors/SbCylinderSectionProjector.cpp \
           database/src/projectors/SbCylinderSheetProjector.cpp \
           database/src/projectors/SbLineProjector.cpp \
           database/src/projectors/SbPlaneProjector.cpp \
           database/src/projectors/SbProjector.cpp \
           database/src/projectors/SbSpherePlaneProjector.cpp \
           database/src/projectors/SbSphereProjector.cpp \
           database/src/projectors/SbSphereSectionProjector.cpp \
           database/src/projectors/SbSphereSheetProjector.cpp \
           database/src/threads/SbThreadMutex.cpp \
           database/src/actions/SoAction.cpp \
           database/src/actions/SoActionMethodList.cpp \
           database/src/actions/SoEnabledElementsList.cpp \
           database/src/actions/SoActionInit.cpp \
           database/src/actions/SoCallbackAction.cpp \
           database/src/actions/SoGetBoundingBoxAction.cpp \
           database/src/actions/SoGetMatrixAction.cpp \
           database/src/actions/SoGLRenderAction.cpp \
           database/src/actions/SoHandleEventAction.cpp \
           database/src/actions/SoPickAction.cpp \
           database/src/actions/SoRayPickAction.cpp \
           database/src/actions/SoSearchAction.cpp \
           database/src/actions/SoWriteAction.cpp \
           database/src/bundles/SoMaterialBundle.cpp \
           database/src/bundles/SoNormalBundle.cpp \
           database/src/bundles/SoTextureCoordinateBundle.cpp \
           database/src/caches/SoBitmapFontCache.cpp \
           database/src/caches/SoOutlineFontCache.cpp \
           database/src/caches/SoFontOutline.cpp \
           database/src/caches/SoBoundingBoxCache.cpp \
           database/src/caches/SoCache.cpp \
           database/src/caches/SoGLCacheList.cpp \
           database/src/caches/SoGLDisplayList.cpp \
           database/src/caches/SoGLRenderCache.cpp \
           database/src/caches/SoNormalCache.cpp \
           database/src/caches/SoVertexPropertyCache.cpp \
           database/src/details/SoConeDetail.cpp \
           database/src/details/SoCubeDetail.cpp \
           database/src/details/SoCylinderDetail.cpp \
           database/src/details/SoDetail.cpp \
           database/src/details/SoDetailInit.cpp \
           database/src/details/SoFaceDetail.cpp \
           database/src/details/SoLineDetail.cpp \
           database/src/details/SoPointDetail.cpp \
           database/src/details/SoTextDetail.cpp \
           database/src/elements/SoAccumulatedElement.cpp \
           database/src/elements/SoBBoxModelMatrixElement.cpp \
           database/src/elements/SoCacheElement.cpp \
           database/src/elements/SoClipPlaneElement.cpp \
           database/src/elements/SoComplexityElement.cpp \
           database/src/elements/SoComplexityTypeElement.cpp \
           database/src/elements/SoCoordinateElement.cpp \
           database/src/elements/SoCreaseAngleElement.cpp \
           database/src/elements/SoDepthBufferElement.cpp \
           database/src/elements/SoDrawStyleElement.cpp \
           database/src/elements/SoElement.cpp \
           database/src/elements/SoElementInit.cpp \
           database/src/elements/SoFloatElement.cpp \
           database/src/elements/SoFocalDistanceElement.cpp \
           database/src/elements/SoFontNameElement.cpp \
           database/src/elements/SoFontSizeElement.cpp \
           database/src/elements/SoGLCacheContextElement.cpp \
           database/src/elements/SoGLDepthBufferElement.cpp \
           database/src/elements/SoGLClipPlaneElement.cpp \
           database/src/elements/SoGLCoordinateElement.cpp \
           database/src/elements/SoGLDrawStyleElement.cpp \
           database/src/elements/SoGLLazyElement.cpp \
           database/src/elements/SoGLLightIdElement.cpp \
           database/src/elements/SoGLLinePatternElement.cpp \
           database/src/elements/SoGLLineWidthElement.cpp \
           database/src/elements/SoGLModelMatrixElement.cpp \
           database/src/elements/SoGLNormalElement.cpp \
           database/src/elements/SoGLPointSizeElement.cpp \
           database/src/elements/SoGLPolygonOffsetElement.cpp \
           database/src/elements/SoGLProjectionMatrixElement.cpp \
           database/src/elements/SoGLRenderPassElement.cpp \
           database/src/elements/SoGLShapeHintsElement.cpp \
           database/src/elements/SoGLTextureCoordinateElement.cpp \
           database/src/elements/SoGLTextureEnabledElement.cpp \
           database/src/elements/SoGLTextureImageElement.cpp \
           database/src/elements/SoGLTextureMatrixElement.cpp \
           database/src/elements/SoGLTextureCoordinate3Element.cpp \
           database/src/elements/SoGLTextureUnitElement.cpp \
           database/src/elements/SoGLUpdateAreaElement.cpp \
           database/src/elements/SoGLViewingMatrixElement.cpp \
           database/src/elements/SoGLViewportRegionElement.cpp \
           database/src/elements/SoInt32Element.cpp \
           database/src/elements/SoLazyElement.cpp \
           database/src/elements/SoLightAttenuationElement.cpp \
           database/src/elements/SoLinePatternElement.cpp \
           database/src/elements/SoLineWidthElement.cpp \
           database/src/elements/SoLocalBBoxMatrixElement.cpp \
           database/src/elements/SoMaterialBindingElement.cpp \
           database/src/elements/SoModelMatrixElement.cpp \
           database/src/elements/SoNormalBindingElement.cpp \
           database/src/elements/SoNormalElement.cpp \
           database/src/elements/SoOverrideElement.cpp \
           database/src/elements/SoPickRayElement.cpp \
           database/src/elements/SoPickStyleElement.cpp \
           database/src/elements/SoPointSizeElement.cpp \
           database/src/elements/SoPolygonOffsetElement.cpp \
           database/src/elements/SoProfileCoordinateElement.cpp \
           database/src/elements/SoProfileElement.cpp \
           database/src/elements/SoProjectionMatrixElement.cpp \
           database/src/elements/SoReplacedElement.cpp \
           database/src/elements/SoShapeHintsElement.cpp \
           database/src/elements/SoShapeStyleElement.cpp \
           database/src/elements/SoStereoElement.cpp \
           database/src/elements/SoSwitchElement.cpp \
           database/src/elements/SoTextureCoordinateBindingElement.cpp \
           database/src/elements/SoTextureCoordinateElement.cpp \
           database/src/elements/SoTextureImageElement.cpp \
           database/src/elements/SoTextureMatrixElement.cpp \
           database/src/elements/SoTextureQualityElement.cpp \
           database/src/elements/SoTextureCoordinate3Element.cpp \
           database/src/elements/SoTextureUnitElement.cpp \
           database/src/elements/SoTransparencyTypeElement.cpp \
           database/src/elements/SoUnitsElement.cpp \
           database/src/elements/SoViewingMatrixElement.cpp \
           database/src/elements/SoViewportRegionElement.cpp \
           database/src/elements/SoViewVolumeElement.cpp \
           database/src/engines/SoBoolOperation.cpp \
           database/src/engines/SoCalcExpr.cpp \
           database/src/engines/SoCalculator.cpp \
           database/src/engines/SoCompose.cpp \
           database/src/engines/SoComputeBoundingBox.cpp \
           database/src/engines/SoConcatenate.cpp \
           database/src/engines/SoCounter.cpp \
           database/src/engines/SoElapsedTime.cpp \
           database/src/engines/SoEngine.cpp \
           database/src/engines/SoEngineOutput.cpp \
           database/src/engines/SoEngineInit.cpp \
           database/src/engines/SoFieldConverter.cpp \
           database/src/engines/SoFieldConverters.cpp \
           database/src/engines/SoGate.cpp \
           database/src/engines/SoInterpolate.cpp \
           database/src/engines/SoOneShot.cpp \
           database/src/engines/SoOnOff.cpp \
           database/src/engines/SoOutputData.cpp \
           database/src/engines/SoSelectOne.cpp \
           database/src/engines/SoTimeCounter.cpp \
           database/src/engines/SoTransformVec3f.cpp \
           database/src/engines/SoTriggerAny.cpp \
           database/src/engines/SoUnknownEngine.cpp \
           database/src/errors/SoDebugError.cpp \
           database/src/errors/SoError.cpp \
           database/src/errors/SoErrorInit.cpp \
           database/src/errors/SoMemoryError.cpp \
           database/src/errors/SoReadError.cpp \
           database/src/events/SoButtonEvent.cpp \
           database/src/events/SoEvent.cpp \
           database/src/events/SoEventInit.cpp \
           database/src/events/SoKeyboardEvent.cpp \
           database/src/events/SoLocation2Event.cpp \
           database/src/events/SoMotion3Event.cpp \
           database/src/events/SoMouseButtonEvent.cpp \
           database/src/events/SoSpaceballButtonEvent.cpp \
           database/src/events/SoControllerButtonEvent.cpp \
           database/src/events/SbTrackerInfo.cpp \
           database/src/events/SoTrackerEvent.cpp \
           database/src/fields/SoField.cpp \
           database/src/fields/SoSField.cpp \
           database/src/fields/SoMField.cpp \
           database/src/fields/SoFieldContainer.cpp \
           database/src/fields/SoFieldData.cpp \
           database/src/fields/SoFieldInit.cpp \
           database/src/fields/SoGlobalField.cpp \
           database/src/fields/SoMFBitMask.cpp \
           database/src/fields/SoMFBool.cpp \
           database/src/fields/SoMFColor.cpp \
           database/src/fields/SoMFEngine.cpp \
           database/src/fields/SoMFEnum.cpp \
           database/src/fields/SoMFFloat.cpp \
           database/src/fields/SoMFInt32.cpp \
           database/src/fields/SoMFMatrix.cpp \
           database/src/fields/SoMFName.cpp \
           database/src/fields/SoMFNode.cpp \
           database/src/fields/SoMFPath.cpp \
           database/src/fields/SoMFPlane.cpp \
           database/src/fields/SoMFRotation.cpp \
           database/src/fields/SoMFShort.cpp \
           database/src/fields/SoMFString.cpp \
           database/src/fields/SoMFTime.cpp \
           database/src/fields/SoMFUInt32.cpp \
           database/src/fields/SoMFUShort.cpp \
           database/src/fields/SoMFVec2f.cpp \
           database/src/fields/SoMFVec3f.cpp \
           database/src/fields/SoMFVec3i32.cpp \
           database/src/fields/SoMFVec4f.cpp \
           database/src/fields/SoMFVec4i32.cpp \
           database/src/fields/SoSFBitMask.cpp \
           database/src/fields/SoSFBool.cpp \
           database/src/fields/SoSFBox3f.cpp \
           database/src/fields/SoSFColor.cpp \
           database/src/fields/SoSFEngine.cpp \
           database/src/fields/SoSFEnum.cpp \
           database/src/fields/SoSFFloat.cpp \
           database/src/fields/SoSFImage.cpp \
           database/src/fields/SoSFInt32.cpp \
           database/src/fields/SoSFMatrix.cpp \
           database/src/fields/SoSFName.cpp \
           database/src/fields/SoSFNode.cpp \
           database/src/fields/SoSFPath.cpp \
           database/src/fields/SoSFPlane.cpp \
           database/src/fields/SoSFRotation.cpp \
           database/src/fields/SoSFShort.cpp \
           database/src/fields/SoSFString.cpp \
           database/src/fields/SoSFTime.cpp \
           database/src/fields/SoSFTrigger.cpp \
           database/src/fields/SoSFUInt32.cpp \
           database/src/fields/SoSFUShort.cpp \
           database/src/fields/SoSFVec2f.cpp \
           database/src/fields/SoSFVec3f.cpp \
           database/src/fields/SoSFVec4f.cpp \
           database/src/misc/SoGLContext.cpp \
           database/src/nodes/SoAnnotation.cpp \
           database/src/nodes/SoArray.cpp \
           database/src/nodes/SoAsciiText.cpp \
           database/src/nodes/SoBaseColor.cpp \
           database/src/nodes/SoBlinker.cpp \
           database/src/nodes/SoCallback.cpp \
           database/src/nodes/SoCamera.cpp \
           database/src/nodes/SoClipPlane.cpp \
           database/src/nodes/SoColorIndex.cpp \
           database/src/nodes/SoComplexity.cpp \
           database/src/nodes/SoCone.cpp \
           database/src/nodes/SoCoordinate3.cpp \
           database/src/nodes/SoCoordinate4.cpp \
           database/src/nodes/SoCube.cpp \
           database/src/nodes/SoCylinder.cpp \
           database/src/nodes/SoDepthBuffer.cpp \
           database/src/nodes/SoDirectionalLight.cpp \
           database/src/nodes/SoDrawStyle.cpp \
           database/src/nodes/SoEnvironment.cpp \
           database/src/nodes/SoEventCallback.cpp \
           database/src/nodes/SoFaceSet.cpp \
           database/src/nodes/SoFile.cpp \
           database/src/nodes/SoFont.cpp \
           database/src/nodes/SoFontStyle.cpp \
           database/src/nodes/SoGroup.cpp \
           database/src/nodes/SoIndexedFaceSet.cpp \
           database/src/nodes/SoIndexedLineSet.cpp \
           database/src/nodes/SoIndexedNurbsCurve.cpp \
           database/src/nodes/SoIndexedNurbsSurface.cpp \
           database/src/nodes/SoIndexedPointSet.cpp \
           database/src/nodes/SoIndexedShape.cpp \
           database/src/nodes/SoIndexedTriangleStripSet.cpp \
           database/src/nodes/SoInfo.cpp \
           database/src/nodes/SoLabel.cpp \
           database/src/nodes/SoLevelOfDetail.cpp \
           database/src/nodes/SoLight.cpp \
           database/src/nodes/SoLightModel.cpp \
           database/src/nodes/SoLinearProfile.cpp \
           database/src/nodes/SoLineSet.cpp \
           database/src/nodes/SoLocateHighlight.cpp \
           database/src/nodes/SoLOD.cpp \
           database/src/nodes/SoMaterial.cpp \
           database/src/nodes/SoMaterialBinding.cpp \
           database/src/nodes/SoMatrixTransform.cpp \
           database/src/nodes/SoMultipleCopy.cpp \
           database/src/nodes/SoNode.cpp \
           database/src/nodes/SoNodeInit.cpp \
           database/src/nodes/SoNonIndexedShape.cpp \
           database/src/nodes/SoNormal.cpp \
           database/src/nodes/SoNormalBinding.cpp \
           database/src/nodes/SoNurbsCurve.cpp \
           database/src/nodes/SoNurbsProfile.cpp \
           database/src/nodes/SoNurbsSurface.cpp \
           database/src/nodes/SoOrthographicCamera.cpp \
           database/src/nodes/SoPackedColor.cpp \
           database/src/nodes/SoPathSwitch.cpp \
           database/src/nodes/SoPendulum.cpp \
           database/src/nodes/SoPerspectiveCamera.cpp \
           database/src/nodes/SoPickStyle.cpp \
           database/src/nodes/SoPointLight.cpp \
           database/src/nodes/SoPointSet.cpp \
           database/src/nodes/SoPolygonOffset.cpp \
           database/src/nodes/SoProfile.cpp \
           database/src/nodes/SoProfileCoordinate2.cpp \
           database/src/nodes/SoProfileCoordinate3.cpp \
           database/src/nodes/SoQuadMesh.cpp \
           database/src/nodes/SoResetTransform.cpp \
           database/src/nodes/SoRotation.cpp \
           database/src/nodes/SoRotationXYZ.cpp \
           database/src/nodes/SoRotor.cpp \
           database/src/nodes/SoScale.cpp \
           database/src/nodes/SoSeparator.cpp \
           database/src/nodes/SoShape.cpp \
           database/src/nodes/SoShapeHints.cpp \
           database/src/nodes/SoShuttle.cpp \
           database/src/nodes/SoSphere.cpp \
           database/src/nodes/SoSpotLight.cpp \
           database/src/nodes/SoSwitch.cpp \
           database/src/nodes/SoText2.cpp \
           database/src/nodes/SoText3.cpp \
           database/src/nodes/SoTexture2.cpp \
           database/src/nodes/SoTexture2Transform.cpp \
           database/src/nodes/SoTextureCoordinate2.cpp \
           database/src/nodes/SoTextureCoordinateBinding.cpp \
           database/src/nodes/SoTextureCoordinateDefault.cpp \
           database/src/nodes/SoTextureCoordinateEnvironment.cpp \
           database/src/nodes/SoTextureCoordinateFunction.cpp \
           database/src/nodes/SoTextureCoordinateObject.cpp \
           database/src/nodes/SoTextureCoordinatePlane.cpp \
           database/src/nodes/SoTextureCoordinate3.cpp \
           database/src/nodes/SoTextureUnit.cpp \
           database/src/nodes/SoTransform.cpp \
           database/src/nodes/SoTransformation.cpp \
           database/src/nodes/SoTransformSeparator.cpp \
           database/src/nodes/SoTranslation.cpp \
           database/src/nodes/SoTransparencyType.cpp \
           database/src/nodes/SoTriangleStripSet.cpp \
           database/src/nodes/SoUnits.cpp \
           database/src/nodes/SoUnknownNode.cpp \
           database/src/nodes/SoVertexProperty.cpp \
           database/src/nodes/SoVertexShape.cpp \
           database/src/nodes/SoWWWAnchor.cpp \
           database/src/nodes/SoWWWInline.cpp \
           database/src/sensors/SoAlarmSensor.cpp \
           database/src/sensors/SoDataSensor.cpp \
           database/src/sensors/SoDelayQueueSensor.cpp \
           database/src/sensors/SoFieldSensor.cpp \
           database/src/sensors/SoIdleSensor.cpp \
           database/src/sensors/SoNodeSensor.cpp \
           database/src/sensors/SoOneShotSensor.cpp \
           database/src/sensors/SoPathSensor.cpp \
           database/src/sensors/SoSensor.cpp \
           database/src/sensors/SoSensorManager.cpp \
           database/src/sensors/SoTimerQueueSensor.cpp \
           database/src/sensors/SoTimerSensor.cpp \
           database/src/upgraders/SoUpgrader.cpp \
           database/src/upgraders/SoUpgraderInit.cpp \
           database/src/upgraders/SoV1CustomNode.cpp \
           database/src/upgraders/SoV1DrawStyle.cpp \
           database/src/upgraders/SoV1Environment.cpp \
           database/src/upgraders/SoV1IndexedTriangleMesh.cpp \
           database/src/upgraders/SoV1LayerGroup.cpp \
           database/src/upgraders/SoV1LightModel.cpp \
           database/src/upgraders/SoV1Material.cpp \
           database/src/upgraders/SoV1PackedColor.cpp \
           database/src/upgraders/SoV1PickStyle.cpp \
           database/src/upgraders/SoV1Separator.cpp \
           database/src/upgraders/SoV1ShapeHints.cpp \
           database/src/upgraders/SoV1Text2.cpp \
           database/src/upgraders/SoV1Text3.cpp \
           database/src/upgraders/SoV1Texture2.cpp \
           database/src/upgraders/SoV1TextureCoordinateCube.cpp \
           database/src/upgraders/SoV1TextureCoordinateCylinder.cpp \
           database/src/upgraders/SoV1TextureCoordinateEnvironment.cpp \
           database/src/upgraders/SoV1TextureCoordinatePlane.cpp \
           database/src/upgraders/SoV1TextureCoordinateSphere.cpp \
           database/src/upgraders/SoV2AsciiText.cpp \
           database/src/upgraders/SoV2FontStyle.cpp \
           database/src/upgraders/SoV2LOD.cpp \
           database/src/upgraders/SoV2MaterialIndex.cpp \
           database/src/upgraders/SoV2Text2.cpp \
           database/src/upgraders/SoV2Text3.cpp \
           database/src/upgraders/SoV2VertexProperty.cpp \
           database/src/upgraders/SoV2WWWAnchor.cpp \
           database/src/upgraders/SoV2WWWInline.cpp
