#!/bin/bash

#
# Prepares command line info to create a man page for the given class name
#
# Usage: makeManDirs className
#

toolDir="../../ivman"
className=$1
treeFile="$toolDir/manTree"

# Get the list of derived classes
classes=$(grep "^$className " $treeFile)

# For each class, find the directory containing the man page. Build
# a final list from the {className,dir} pairs.
list=""
for class in $classes
do
    path=$(find . -name $class.ivm | cut -c3-)
    if [ -e $path ]; then
	list="$list $path"
    fi
done

# Print the result
echo $list
