######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:54:45 2011
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += longToInt32.pro
