######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 22:05:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += example.cpp
