######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 22:06:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += foo.h
SOURCES += ivToIncludeFile.cpp testResults.cpp
