######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 22:08:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += RevClass.h
SOURCES += profile.cpp RevClass.cpp revo.cpp
