######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:54:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Edges.h Faces.h FindNormals.h
SOURCES += Edges.cpp Faces.cpp FindNormals.cpp ivnorm.cpp
