# for nurbs...
DEFINES += LIBRARYBUILD

DEPENDPATH += database \
              database/include \
              database/include/Inventor \
              database/src/sb \
              database/src/so \
              database/include/Inventor/actions \
              database/include/Inventor/bundles \
              database/include/Inventor/caches \
              database/include/Inventor/details \
              database/include/Inventor/elements \
              database/include/Inventor/engines \
              database/include/Inventor/errors \
              database/include/Inventor/events \
              database/include/Inventor/fields \
              database/include/Inventor/misc \
              database/include/Inventor/nodes \
              database/include/Inventor/projectors \
              database/include/Inventor/sensors \
              database/src/sb/projectors \
              database/src/so/actions \
              database/src/so/bundles \
              database/src/so/caches \
              database/src/so/details \
              database/src/so/elements \
              database/src/so/engines \
              database/src/so/errors \
              database/src/so/events \
              database/src/so/fields \
              database/src/so/nodes \
              database/src/so/sensors \
              database/src/so/upgraders \
              database/include/Inventor/misc/upgraders \
              database/src/so/nodes/nurbs \
              database/src/so/nodes/nurbs/clients \
              database/src/so/nodes/nurbs/head \
              database/src/so/nodes/nurbs/libnurbs

INCLUDEPATH += ../libFL/src \
               database/src/so/nodes/nurbs/head/



PUBLIC_HEADERS += database/include/machine.h \
           database/include/SoDebug.h \
           database/include/SoUnknownEngine.h \
           database/include/SoUnknownNode.h \
           database/include/Inventor/Sb.h \
           database/include/Inventor/SbBasic.h \
           database/include/Inventor/SbBox.h \
           database/include/Inventor/SbBox3f.h \
           database/include/Inventor/SbXfBox3f.h \
           database/include/Inventor/SbBox2f.h \
           database/include/Inventor/SbBox2s.h \
           database/include/Inventor/SbColor.h \
           database/include/Inventor/SbDict.h \
           database/include/Inventor/SbStdint.h \
           database/include/Inventor/SbLinear.h \
           database/include/Inventor/SbName.h \
           database/include/Inventor/SbNameEntry.h \
           database/include/Inventor/SbVec2f.h \
           database/include/Inventor/SbVec2s.h \
           database/include/Inventor/SbVec3f.h \
           database/include/Inventor/SbVec3d.h \
           database/include/Inventor/SbVec4f.h \
           database/include/Inventor/SbMatrix.h \
           database/include/Inventor/SbRotation.h \
           database/include/Inventor/SbLine.h \
           database/include/Inventor/SbPlane.h \
           database/include/Inventor/SbSphere.h \
           database/include/Inventor/SbCylinder.h \
           database/include/Inventor/SbViewVolume.h \
           database/include/Inventor/SbPList.h \
           database/include/Inventor/SbString.h \
           database/include/Inventor/SbTime.h \
           database/include/Inventor/SbViewportRegion.h \
           database/include/Inventor/So.h \
           database/include/Inventor/SoDB.h \
           database/include/Inventor/SoInput.h \
           database/include/Inventor/SoLists.h \
           database/include/Inventor/SoOffscreenRenderer.h \
           database/include/Inventor/SoOutput.h \
           database/include/Inventor/SoPath.h \
           database/include/Inventor/SoFullPath.h \
           database/include/Inventor/SoLightPath.h \
           database/include/Inventor/SoPickedPoint.h \
           database/include/Inventor/SoPrimitiveVertex.h \
           database/include/Inventor/SoType.h \
           database/include/Inventor/actions/SoAction.h \
           database/include/Inventor/actions/SoActionMethodList.h \
           database/include/Inventor/actions/SoEnabledElementsList.h \
           database/include/Inventor/actions/SoActions.h \
           database/include/Inventor/actions/SoCallbackAction.h \
           database/include/Inventor/actions/SoGetBoundingBoxAction.h \
           database/include/Inventor/actions/SoGetMatrixAction.h \
           database/include/Inventor/actions/SoGLRenderAction.h \
           database/include/Inventor/actions/SoHandleEventAction.h \
           database/include/Inventor/actions/SoPickAction.h \
           database/include/Inventor/actions/SoRayPickAction.h \
           database/include/Inventor/actions/SoSearchAction.h \
           database/include/Inventor/actions/SoSubAction.h \
           database/include/Inventor/actions/SoWriteAction.h \
           database/include/Inventor/bundles/SoBundle.h \
           database/include/Inventor/bundles/SoMaterialBundle.h \
           database/include/Inventor/bundles/SoNormalBundle.h \
           database/include/Inventor/bundles/SoTextureCoordinateBundle.h \
           database/include/Inventor/caches/SoBoundingBoxCache.h \
           database/include/Inventor/caches/SoCache.h \
           database/include/Inventor/caches/SoGLCacheList.h \
           database/include/Inventor/caches/SoGLRenderCache.h \
           database/include/Inventor/caches/SoNormalCache.h \
           database/include/Inventor/caches/SoVertexPropertyCache.h \
           database/include/Inventor/details/SoConeDetail.h \
           database/include/Inventor/details/SoCubeDetail.h \
           database/include/Inventor/details/SoCylinderDetail.h \
           database/include/Inventor/details/SoDetail.h \
           database/include/Inventor/details/SoDetails.h \
           database/include/Inventor/details/SoFaceDetail.h \
           database/include/Inventor/details/SoLineDetail.h \
           database/include/Inventor/details/SoPointDetail.h \
           database/include/Inventor/details/SoSubDetail.h \
           database/include/Inventor/details/SoTextDetail.h \
           database/include/Inventor/elements/SoAccumulatedElement.h \
           database/include/Inventor/elements/SoBBoxModelMatrixElement.h \
           database/include/Inventor/elements/SoCacheElement.h \
           database/include/Inventor/elements/SoClipPlaneElement.h \
           database/include/Inventor/elements/SoComplexityElement.h \
           database/include/Inventor/elements/SoComplexityTypeElement.h \
           database/include/Inventor/elements/SoCoordinateElement.h \
           database/include/Inventor/elements/SoCreaseAngleElement.h \
           database/include/Inventor/elements/SoDrawStyleElement.h \
           database/include/Inventor/elements/SoElement.h \
           database/include/Inventor/elements/SoElements.h \
           database/include/Inventor/elements/SoFloatElement.h \
           database/include/Inventor/elements/SoFocalDistanceElement.h \
           database/include/Inventor/elements/SoFontNameElement.h \
           database/include/Inventor/elements/SoFontSizeElement.h \
           database/include/Inventor/elements/SoGLCacheContextElement.h \
           database/include/Inventor/elements/SoGLClipPlaneElement.h \
           database/include/Inventor/elements/SoGLCoordinateElement.h \
           database/include/Inventor/elements/SoGLDrawStyleElement.h \
           database/include/Inventor/elements/SoGLLazyElement.h \
           database/include/Inventor/elements/SoGLLightIdElement.h \
           database/include/Inventor/elements/SoGLLinePatternElement.h \
           database/include/Inventor/elements/SoGLLineWidthElement.h \
           database/include/Inventor/elements/SoGLModelMatrixElement.h \
           database/include/Inventor/elements/SoGLNormalElement.h \
           database/include/Inventor/elements/SoGLPointSizeElement.h \
           database/include/Inventor/elements/SoGLProjectionMatrixElement.h \
           database/include/Inventor/elements/SoGLRenderPassElement.h \
           database/include/Inventor/elements/SoGLShapeHintsElement.h \
           database/include/Inventor/elements/SoGLTextureCoordinateElement.h \
           database/include/Inventor/elements/SoGLTextureEnabledElement.h \
           database/include/Inventor/elements/SoGLTextureImageElement.h \
           database/include/Inventor/elements/SoGLTextureMatrixElement.h \
           database/include/Inventor/elements/SoGLUpdateAreaElement.h \
           database/include/Inventor/elements/SoGLViewingMatrixElement.h \
           database/include/Inventor/elements/SoGLViewportRegionElement.h \
           database/include/Inventor/elements/SoInt32Element.h \
           database/include/Inventor/elements/SoLazyElement.h \
           database/include/Inventor/elements/SoLightAttenuationElement.h \
           database/include/Inventor/elements/SoLinePatternElement.h \
           database/include/Inventor/elements/SoLineWidthElement.h \
           database/include/Inventor/elements/SoLocalBBoxMatrixElement.h \
           database/include/Inventor/elements/SoMaterialBindingElement.h \
           database/include/Inventor/elements/SoModelMatrixElement.h \
           database/include/Inventor/elements/SoNormalBindingElement.h \
           database/include/Inventor/elements/SoNormalElement.h \
           database/include/Inventor/elements/SoOverrideElement.h \
           database/include/Inventor/elements/SoPickRayElement.h \
           database/include/Inventor/elements/SoPickStyleElement.h \
           database/include/Inventor/elements/SoPointSizeElement.h \
           database/include/Inventor/elements/SoProfileCoordinateElement.h \
           database/include/Inventor/elements/SoProfileElement.h \
           database/include/Inventor/elements/SoProjectionMatrixElement.h \
           database/include/Inventor/elements/SoReplacedElement.h \
           database/include/Inventor/elements/SoShapeHintsElement.h \
           database/include/Inventor/elements/SoShapeStyleElement.h \
           database/include/Inventor/elements/SoSpecularColorElement.h \
           database/include/Inventor/elements/SoSubElement.h \
           database/include/Inventor/elements/SoSwitchElement.h \
           database/include/Inventor/elements/SoTextureCoordinateBindingElement.h \
           database/include/Inventor/elements/SoTextureCoordinateElement.h \
           database/include/Inventor/elements/SoTextureImageElement.h \
           database/include/Inventor/elements/SoTextureMatrixElement.h \
           database/include/Inventor/elements/SoTextureQualityElement.h \
           database/include/Inventor/elements/SoUnitsElement.h \
           database/include/Inventor/elements/SoViewingMatrixElement.h \
           database/include/Inventor/elements/SoViewportRegionElement.h \
           database/include/Inventor/elements/SoViewVolumeElement.h \
           database/include/Inventor/elements/SoWindowElement.h \
           database/include/Inventor/engines/SoBoolOperation.h \
           database/include/Inventor/engines/SoCalculator.h \
           database/include/Inventor/engines/SoCompose.h \
           database/include/Inventor/engines/SoComputeBoundingBox.h \
           database/include/Inventor/engines/SoConcatenate.h \
           database/include/Inventor/engines/SoCounter.h \
           database/include/Inventor/engines/SoElapsedTime.h \
           database/include/Inventor/engines/SoEngine.h \
           database/include/Inventor/engines/SoEngines.h \
           database/include/Inventor/engines/SoFieldConverter.h \
           database/include/Inventor/engines/SoGate.h \
           database/include/Inventor/engines/SoInterpolate.h \
           database/include/Inventor/engines/SoOneShot.h \
           database/include/Inventor/engines/SoOnOff.h \
           database/include/Inventor/engines/SoOutputData.h \
           database/include/Inventor/engines/SoSelectOne.h \
           database/include/Inventor/engines/SoSubEngine.h \
           database/include/Inventor/engines/SoTimeCounter.h \
           database/include/Inventor/engines/SoTransformVec3f.h \
           database/include/Inventor/engines/SoTriggerAny.h \
           database/include/Inventor/errors/SoDebugError.h \
           database/include/Inventor/errors/SoError.h \
           database/include/Inventor/errors/SoErrors.h \
           database/include/Inventor/errors/SoMemoryError.h \
           database/include/Inventor/errors/SoReadError.h \
           database/include/Inventor/events/SoButtonEvent.h \
           database/include/Inventor/events/SoEvent.h \
           database/include/Inventor/events/SoEvents.h \
           database/include/Inventor/events/SoKeyboardEvent.h \
           database/include/Inventor/events/SoLocation2Event.h \
           database/include/Inventor/events/SoMotion3Event.h \
           database/include/Inventor/events/SoMouseButtonEvent.h \
           database/include/Inventor/events/SoSpaceballButtonEvent.h \
           database/include/Inventor/events/SoSubEvent.h \
           database/include/Inventor/fields/SoField.h \
           database/include/Inventor/fields/SoSField.h \
           database/include/Inventor/fields/SoMField.h \
           database/include/Inventor/fields/SoFieldContainer.h \
           database/include/Inventor/fields/SoFieldData.h \
           database/include/Inventor/fields/SoFields.h \
           database/include/Inventor/fields/SoMFBitMask.h \
           database/include/Inventor/fields/SoMFBool.h \
           database/include/Inventor/fields/SoMFColor.h \
           database/include/Inventor/fields/SoMFEngine.h \
           database/include/Inventor/fields/SoMFEnum.h \
           database/include/Inventor/fields/SoMFFloat.h \
           database/include/Inventor/fields/SoMFInt32.h \
           database/include/Inventor/fields/SoMFMatrix.h \
           database/include/Inventor/fields/SoMFName.h \
           database/include/Inventor/fields/SoMFNode.h \
           database/include/Inventor/fields/SoMFPath.h \
           database/include/Inventor/fields/SoMFPlane.h \
           database/include/Inventor/fields/SoMFRotation.h \
           database/include/Inventor/fields/SoMFShort.h \
           database/include/Inventor/fields/SoMFString.h \
           database/include/Inventor/fields/SoMFTime.h \
           database/include/Inventor/fields/SoMFUInt32.h \
           database/include/Inventor/fields/SoMFUShort.h \
           database/include/Inventor/fields/SoMFVec2f.h \
           database/include/Inventor/fields/SoMFVec3f.h \
           database/include/Inventor/fields/SoMFVec4f.h \
           database/include/Inventor/fields/SoSFBitMask.h \
           database/include/Inventor/fields/SoSFBool.h \
           database/include/Inventor/fields/SoSFBox3f.h \
           database/include/Inventor/fields/SoSFColor.h \
           database/include/Inventor/fields/SoSFEngine.h \
           database/include/Inventor/fields/SoSFEnum.h \
           database/include/Inventor/fields/SoSFFloat.h \
           database/include/Inventor/fields/SoSFImage.h \
           database/include/Inventor/fields/SoSFInt32.h \
           database/include/Inventor/fields/SoSFMatrix.h \
           database/include/Inventor/fields/SoSFName.h \
           database/include/Inventor/fields/SoSFNode.h \
           database/include/Inventor/fields/SoSFPath.h \
           database/include/Inventor/fields/SoSFPlane.h \
           database/include/Inventor/fields/SoSFRotation.h \
           database/include/Inventor/fields/SoSFShort.h \
           database/include/Inventor/fields/SoSFString.h \
           database/include/Inventor/fields/SoSFTime.h \
           database/include/Inventor/fields/SoSFTrigger.h \
           database/include/Inventor/fields/SoSFUInt32.h \
           database/include/Inventor/fields/SoSFUShort.h \
           database/include/Inventor/fields/SoSFVec2f.h \
           database/include/Inventor/fields/SoSFVec3f.h \
           database/include/Inventor/fields/SoSFVec4f.h \
           database/include/Inventor/fields/SoSubField.h \
           database/include/Inventor/lists/SbIntList.h \
           database/include/Inventor/lists/SbVec3fList.h \
           database/include/Inventor/lists/SbStringList.h \
           database/include/Inventor/lists/SoBaseList.h \
           database/include/Inventor/lists/SoNodeList.h \
           database/include/Inventor/lists/SoPathList.h \
           database/include/Inventor/lists/SoEngineList.h \
           database/include/Inventor/lists/SoTypeList.h \
           database/include/Inventor/lists/SoDetailList.h \
           database/include/Inventor/lists/SoPickedPointList.h \
           database/include/Inventor/lists/SoFieldList.h \
           database/include/Inventor/lists/SoEngineOutputList.h \
           database/include/Inventor/lists/SoAuditorList.h \
           database/include/Inventor/misc/SoAuditorList.h \
           database/include/Inventor/misc/SoBase.h \
           database/include/Inventor/misc/SoBasic.h \
           database/include/Inventor/misc/SoByteStream.h \
           database/include/Inventor/misc/SoCallbackList.h \
           database/include/Inventor/misc/SoChildList.h \
           database/include/Inventor/misc/SoCompactPathList.h \
           database/include/Inventor/misc/SoGL.h \
           database/include/Inventor/misc/SoNormalGenerator.h \
           database/include/Inventor/misc/SoNotification.h \
           database/include/Inventor/misc/SoState.h \
           database/include/Inventor/misc/SoTempPath.h \
           database/include/Inventor/misc/SoTranscribe.h \
           database/include/Inventor/nodes/SoAnnotation.h \
           database/include/Inventor/nodes/SoArray.h \
           database/include/Inventor/nodes/SoAsciiText.h \
           database/include/Inventor/nodes/SoBaseColor.h \
           database/include/Inventor/nodes/SoBlinker.h \
           database/include/Inventor/nodes/SoCallback.h \
           database/include/Inventor/nodes/SoCamera.h \
           database/include/Inventor/nodes/SoClipPlane.h \
           database/include/Inventor/nodes/SoColorIndex.h \
           database/include/Inventor/nodes/SoComplexity.h \
           database/include/Inventor/nodes/SoCone.h \
           database/include/Inventor/nodes/SoCoordinate3.h \
           database/include/Inventor/nodes/SoCoordinate4.h \
           database/include/Inventor/nodes/SoCube.h \
           database/include/Inventor/nodes/SoCylinder.h \
           database/include/Inventor/nodes/SoDirectionalLight.h \
           database/include/Inventor/nodes/SoDrawStyle.h \
           database/include/Inventor/nodes/SoEnvironment.h \
           database/include/Inventor/nodes/SoEventCallback.h \
           database/include/Inventor/nodes/SoFaceSet.h \
           database/include/Inventor/nodes/SoFile.h \
           database/include/Inventor/nodes/SoFont.h \
           database/include/Inventor/nodes/SoFontStyle.h \
           database/include/Inventor/nodes/SoGroup.h \
           database/include/Inventor/nodes/SoIndexedFaceSet.h \
           database/include/Inventor/nodes/SoIndexedLineSet.h \
           database/include/Inventor/nodes/SoIndexedNurbsCurve.h \
           database/include/Inventor/nodes/SoIndexedNurbsSurface.h \
           database/include/Inventor/nodes/SoIndexedShape.h \
           database/include/Inventor/nodes/SoIndexedTriangleStripSet.h \
           database/include/Inventor/nodes/SoInfo.h \
           database/include/Inventor/nodes/SoLabel.h \
           database/include/Inventor/nodes/SoLevelOfDetail.h \
           database/include/Inventor/nodes/SoLight.h \
           database/include/Inventor/nodes/SoLightModel.h \
           database/include/Inventor/nodes/SoLinearProfile.h \
           database/include/Inventor/nodes/SoLineSet.h \
           database/include/Inventor/nodes/SoLocateHighlight.h \
           database/include/Inventor/nodes/SoLOD.h \
           database/include/Inventor/nodes/SoMaterial.h \
           database/include/Inventor/nodes/SoMaterialBinding.h \
           database/include/Inventor/nodes/SoMatrixTransform.h \
           database/include/Inventor/nodes/SoMultipleCopy.h \
           database/include/Inventor/nodes/SoNode.h \
           database/include/Inventor/nodes/SoNodes.h \
           database/include/Inventor/nodes/SoNonIndexedShape.h \
           database/include/Inventor/nodes/SoNormal.h \
           database/include/Inventor/nodes/SoNormalBinding.h \
           database/include/Inventor/nodes/SoNurbsCurve.h \
           database/include/Inventor/nodes/SoNurbsProfile.h \
           database/include/Inventor/nodes/SoNurbsSurface.h \
           database/include/Inventor/nodes/SoOrthographicCamera.h \
           database/include/Inventor/nodes/SoPackedColor.h \
           database/include/Inventor/nodes/SoPathSwitch.h \
           database/include/Inventor/nodes/SoPendulum.h \
           database/include/Inventor/nodes/SoPerspectiveCamera.h \
           database/include/Inventor/nodes/SoPickStyle.h \
           database/include/Inventor/nodes/SoPointLight.h \
           database/include/Inventor/nodes/SoPointSet.h \
           database/include/Inventor/nodes/SoProfile.h \
           database/include/Inventor/nodes/SoProfileCoordinate2.h \
           database/include/Inventor/nodes/SoProfileCoordinate3.h \
           database/include/Inventor/nodes/SoQuadMesh.h \
           database/include/Inventor/nodes/SoResetTransform.h \
           database/include/Inventor/nodes/SoRotation.h \
           database/include/Inventor/nodes/SoRotationXYZ.h \
           database/include/Inventor/nodes/SoRotor.h \
           database/include/Inventor/nodes/SoScale.h \
           database/include/Inventor/nodes/SoSeparator.h \
           database/include/Inventor/nodes/SoShape.h \
           database/include/Inventor/nodes/SoShapeHints.h \
           database/include/Inventor/nodes/SoShuttle.h \
           database/include/Inventor/nodes/SoSphere.h \
           database/include/Inventor/nodes/SoSpotLight.h \
           database/include/Inventor/nodes/SoSubNode.h \
           database/include/Inventor/nodes/SoSwitch.h \
           database/include/Inventor/nodes/SoText2.h \
           database/include/Inventor/nodes/SoText3.h \
           database/include/Inventor/nodes/SoTexture2.h \
           database/include/Inventor/nodes/SoTexture2Transform.h \
           database/include/Inventor/nodes/SoTextureCoordinate2.h \
           database/include/Inventor/nodes/SoTextureCoordinateBinding.h \
           database/include/Inventor/nodes/SoTextureCoordinateDefault.h \
           database/include/Inventor/nodes/SoTextureCoordinateEnvironment.h \
           database/include/Inventor/nodes/SoTextureCoordinateFunction.h \
           database/include/Inventor/nodes/SoTextureCoordinatePlane.h \
           database/include/Inventor/nodes/SoTransform.h \
           database/include/Inventor/nodes/SoTransformation.h \
           database/include/Inventor/nodes/SoTransformSeparator.h \
           database/include/Inventor/nodes/SoTranslation.h \
           database/include/Inventor/nodes/SoTriangleStripSet.h \
           database/include/Inventor/nodes/SoUnits.h \
           database/include/Inventor/nodes/SoVertexProperty.h \
           database/include/Inventor/nodes/SoVertexShape.h \
           database/include/Inventor/nodes/SoWWWAnchor.h \
           database/include/Inventor/nodes/SoWWWInline.h \
           database/include/Inventor/projectors/SbCylinderPlaneProjector.h \
           database/include/Inventor/projectors/SbCylinderProjector.h \
           database/include/Inventor/projectors/SbCylinderSectionProjector.h \
           database/include/Inventor/projectors/SbCylinderSheetProjector.h \
           database/include/Inventor/projectors/SbLineProjector.h \
           database/include/Inventor/projectors/SbPlaneProjector.h \
           database/include/Inventor/projectors/SbProjector.h \
           database/include/Inventor/projectors/SbProjectors.h \
           database/include/Inventor/projectors/SbSpherePlaneProjector.h \
           database/include/Inventor/projectors/SbSphereProjector.h \
           database/include/Inventor/projectors/SbSphereSectionProjector.h \
           database/include/Inventor/projectors/SbSphereSheetProjector.h \
           database/include/Inventor/sensors/SoAlarmSensor.h \
           database/include/Inventor/sensors/SoDataSensor.h \
           database/include/Inventor/sensors/SoDelayQueueSensor.h \
           database/include/Inventor/sensors/SoFieldSensor.h \
           database/include/Inventor/sensors/SoIdleSensor.h \
           database/include/Inventor/sensors/SoNodeSensor.h \
           database/include/Inventor/sensors/SoOneShotSensor.h \
           database/include/Inventor/sensors/SoPathSensor.h \
           database/include/Inventor/sensors/SoSensor.h \
           database/include/Inventor/sensors/SoSensorManager.h \
           database/include/Inventor/sensors/SoSensors.h \
           database/include/Inventor/sensors/SoTimerQueueSensor.h \
           database/include/Inventor/sensors/SoTimerSensor.h \
           database/include/Inventor/misc/upgraders/SoUpgrader.h \
           database/include/Inventor/misc/upgraders/SoV1CustomNode.h

PRIVATE_HEADERS += database/include/Inventor/caches/SoBitmapFontCache.h \
           database/src/so/engines/SoCalcExpr.h \
           database/src/so/engines/SoEngineUtil.h \
           database/src/so/engines/SoFieldConverters.h \
           database/src/so/fields/SoGlobalField.h \
           database/src/so/upgraders/SoUpgraders.h \
           database/src/so/upgraders/SoV1DrawStyle.h \
           database/src/so/upgraders/SoV1Environment.h \
           database/src/so/upgraders/SoV1IndexedTriangleMesh.h \
           database/src/so/upgraders/SoV1LayerGroup.h \
           database/src/so/upgraders/SoV1LightModel.h \
           database/src/so/upgraders/SoV1Material.h \
           database/src/so/upgraders/SoV1PackedColor.h \
           database/src/so/upgraders/SoV1PickStyle.h \
           database/src/so/upgraders/SoV1Separator.h \
           database/src/so/upgraders/SoV1ShapeHints.h \
           database/src/so/upgraders/SoV1Text2.h \
           database/src/so/upgraders/SoV1Text3.h \
           database/src/so/upgraders/SoV1Texture2.h \
           database/src/so/upgraders/SoV1TextureCoordinateCube.h \
           database/src/so/upgraders/SoV1TextureCoordinateCylinder.h \
           database/src/so/upgraders/SoV1TextureCoordinateEnvironment.h \
           database/src/so/upgraders/SoV1TextureCoordinatePlane.h \
           database/src/so/upgraders/SoV1TextureCoordinateSphere.h \
           database/src/so/upgraders/SoV2AsciiText.h \
           database/src/so/upgraders/SoV2FontStyle.h \
           database/src/so/upgraders/SoV2LOD.h \
           database/src/so/upgraders/SoV2MaterialIndex.h \
           database/src/so/upgraders/SoV2Text2.h \
           database/src/so/upgraders/SoV2Text3.h \
           database/src/so/upgraders/SoV2VertexProperty.h \
           database/src/so/upgraders/SoV2WWWAnchor.h \
           database/src/so/upgraders/SoV2WWWInline.h \
           database/src/so/nodes/nurbs/_defines.h \
           database/src/so/nodes/nurbs/_undefs.h \
           database/src/so/nodes/nurbs/SoAddPrefix.h \
           database/src/so/nodes/nurbs/SoCurveMaps.h \
           database/src/so/nodes/nurbs/SoCurveRender.h \
           database/src/so/nodes/nurbs/SoCurveRenderEval.h \
           database/src/so/nodes/nurbs/SoGLRender.h \
           database/src/so/nodes/nurbs/SoPickEvals.h \
           database/src/so/nodes/nurbs/SoPickMaps.h \
           database/src/so/nodes/nurbs/SoPickRender.h \
           database/src/so/nodes/nurbs/SoPrimEvals.h \
           database/src/so/nodes/nurbs/SoPrimMaps.h \
           database/src/so/nodes/nurbs/SoPrimRender.h \
           database/src/so/nodes/nurbs/clients/gl4base.h \
           database/src/so/nodes/nurbs/clients/gl4curveval.h \
           database/src/so/nodes/nurbs/clients/gl4surfeval.h \
           database/src/so/nodes/nurbs/clients/gl4types.h \
           database/src/so/nodes/nurbs/clients/isocurveeval.h \
           database/src/so/nodes/nurbs/clients/softcurvemaps.h \
           database/src/so/nodes/nurbs/clients/softcurveval.h \
           database/src/so/nodes/nurbs/clients/softcurvmap.h \
           database/src/so/nodes/nurbs/clients/softrenderer.h \
           database/src/so/nodes/nurbs/clients/softsurfacemaps.h \
           database/src/so/nodes/nurbs/clients/softsurfeval.h \
           database/src/so/nodes/nurbs/clients/softsurfmap.h \
           database/src/so/nodes/nurbs/clients/typestringtable.h \
           database/src/so/nodes/nurbs/head/arc.h \
           database/src/so/nodes/nurbs/head/arcsorter.h \
           database/src/so/nodes/nurbs/head/arctess.h \
           database/src/so/nodes/nurbs/head/backend.h \
           database/src/so/nodes/nurbs/head/basiccrveval.h \
           database/src/so/nodes/nurbs/head/basicsurfeval.h \
           database/src/so/nodes/nurbs/head/bezierarc.h \
           database/src/so/nodes/nurbs/head/bin.h \
           database/src/so/nodes/nurbs/head/bufpool.h \
           database/src/so/nodes/nurbs/head/cachingeval.h \
           database/src/so/nodes/nurbs/head/coveandtiler.h \
           database/src/so/nodes/nurbs/head/curve.h \
           database/src/so/nodes/nurbs/head/curvelist.h \
           database/src/so/nodes/nurbs/head/defines.h \
           database/src/so/nodes/nurbs/head/displaylist.h \
           database/src/so/nodes/nurbs/head/displaymode.h \
           database/src/so/nodes/nurbs/head/flist.h \
           database/src/so/nodes/nurbs/head/flistsorter.h \
           database/src/so/nodes/nurbs/head/glimports.h \
           database/src/so/nodes/nurbs/head/gridline.h \
           database/src/so/nodes/nurbs/head/gridtrimvertex.h \
           database/src/so/nodes/nurbs/head/gridvertex.h \
           database/src/so/nodes/nurbs/head/hull.h \
           database/src/so/nodes/nurbs/head/jarcloc.h \
           database/src/so/nodes/nurbs/head/jumpbuffer.h \
           database/src/so/nodes/nurbs/head/knot.h \
           database/src/so/nodes/nurbs/head/knotvector.h \
           database/src/so/nodes/nurbs/head/mapdesc.h \
           database/src/so/nodes/nurbs/head/maplist.h \
           database/src/so/nodes/nurbs/head/mesher.h \
           database/src/so/nodes/nurbs/head/myassert.h \
           database/src/so/nodes/nurbs/head/myglimports.h \
           database/src/so/nodes/nurbs/head/mymath.h \
           database/src/so/nodes/nurbs/head/mysetjmp.h \
           database/src/so/nodes/nurbs/head/mystdio.h \
           database/src/so/nodes/nurbs/head/mystdlib.h \
           database/src/so/nodes/nurbs/head/mystring.h \
           database/src/so/nodes/nurbs/head/nurbsconsts.h \
           database/src/so/nodes/nurbs/head/nurbstess.h \
           database/src/so/nodes/nurbs/head/patch.h \
           database/src/so/nodes/nurbs/head/patchlist.h \
           database/src/so/nodes/nurbs/head/pwlarc.h \
           database/src/so/nodes/nurbs/head/quilt.h \
           database/src/so/nodes/nurbs/head/reader.h \
           database/src/so/nodes/nurbs/head/renderhints.h \
           database/src/so/nodes/nurbs/head/simplemath.h \
           database/src/so/nodes/nurbs/head/slicer.h \
           database/src/so/nodes/nurbs/head/sorter.h \
           database/src/so/nodes/nurbs/head/subdivider.h \
           database/src/so/nodes/nurbs/head/trimline.h \
           database/src/so/nodes/nurbs/head/trimregion.h \
           database/src/so/nodes/nurbs/head/trimvertex.h \
           database/src/so/nodes/nurbs/head/trimvertpool.h \
           database/src/so/nodes/nurbs/head/types.h \
           database/src/so/nodes/nurbs/head/uarray.h \
           database/src/so/nodes/nurbs/head/varray.h

HEADERS += $$PUBLIC_HEADERS $$PRIVATE_HEADERS

SOURCES += database/src/sb/SbBox3f.cpp \
           database/src/sb/SbXfBox3f.cpp \
           database/src/sb/SbBox2f.cpp \
           database/src/sb/SbBox2s.cpp \
           database/src/sb/SbColor.cpp \
           database/src/sb/SbCylinder.cpp \
           database/src/sb/SbDict.cpp \
           database/src/sb/SbLine.cpp \
           database/src/sb/SbMatrix.cpp \
           database/src/sb/SbName.cpp \
           database/src/sb/SbNameEntry.cpp \
           database/src/sb/SbPlane.cpp \
           database/src/sb/SbRotation.cpp \
           database/src/sb/SbSphere.cpp \
           database/src/sb/SbString.cpp \
           database/src/sb/SbTime.cpp \
           database/src/sb/SbVec2f.cpp \
           database/src/sb/SbVec2s.cpp \
           database/src/sb/SbVec3f.cpp \
           database/src/sb/SbVec3d.cpp \
           database/src/sb/SbVec4f.cpp \
           database/src/sb/SbViewVolume.cpp \
           database/src/sb/SbViewportRegion.cpp \
           database/src/sb/lists/SbPList.cpp \
           database/src/sb/lists/SbVec3fList.cpp \
           database/src/so/machine.cpp \
           database/src/so/lists/SoAuditorList.cpp \
           database/src/so/lists/SoBaseList.cpp \
           database/src/so/lists/SoDetailList.cpp \
           database/src/so/lists/SoPathList.cpp \
           database/src/so/lists/SoPickedPointList.cpp \
           database/src/so/lists/SoTypeList.cpp \
           database/src/so/SoBase.cpp \
           database/src/so/SoByteStream.cpp \
           database/src/so/SoCBList.cpp \
           database/src/so/SoChildList.cpp \
           database/src/so/SoCompactPathList.cpp \
           database/src/so/SoDB.cpp \
           database/src/so/SoDebug.cpp \
           database/src/so/SoInput.cpp \
           database/src/so/SoNormalGenerator.cpp \
           database/src/so/SoNotification.cpp \
           database/src/so/SoOffscreenRenderer.cpp \
           database/src/so/SoOutput.cpp \
           database/src/so/SoPath.cpp \
           database/src/so/SoFullPath.cpp \
           database/src/so/SoLightPath.cpp \
           database/src/so/SoPickedPoint.cpp \
           database/src/so/SoPrimitiveVertex.cpp \
           database/src/so/SoState.cpp \
           database/src/so/SoTempPath.cpp \
           database/src/so/SoTranscribe.cpp \
           database/src/so/SoType.cpp \
           database/src/sb/projectors/SbCylinderPlaneProjector.cpp \
           database/src/sb/projectors/SbCylinderProjector.cpp \
           database/src/sb/projectors/SbCylinderSectionProjector.cpp \
           database/src/sb/projectors/SbCylinderSheetProjector.cpp \
           database/src/sb/projectors/SbLineProjector.cpp \
           database/src/sb/projectors/SbPlaneProjector.cpp \
           database/src/sb/projectors/SbProjector.cpp \
           database/src/sb/projectors/SbSpherePlaneProjector.cpp \
           database/src/sb/projectors/SbSphereProjector.cpp \
           database/src/sb/projectors/SbSphereSectionProjector.cpp \
           database/src/sb/projectors/SbSphereSheetProjector.cpp \
           database/src/so/actions/SoAction.cpp \
           database/src/so/actions/SoActionMethodList.cpp \
           database/src/so/actions/SoEnabledElementsList.cpp \
           database/src/so/actions/SoActionInit.cpp \
           database/src/so/actions/SoCallbackAction.cpp \
           database/src/so/actions/SoGetBoundingBoxAction.cpp \
           database/src/so/actions/SoGetMatrixAction.cpp \
           database/src/so/actions/SoGLRenderAction.cpp \
           database/src/so/actions/SoHandleEventAction.cpp \
           database/src/so/actions/SoPickAction.cpp \
           database/src/so/actions/SoRayPickAction.cpp \
           database/src/so/actions/SoSearchAction.cpp \
           database/src/so/actions/SoWriteAction.cpp \
           database/src/so/bundles/SoMaterialBundle.cpp \
           database/src/so/bundles/SoNormalBundle.cpp \
           database/src/so/bundles/SoTextureCoordinateBundle.cpp \
           database/src/so/caches/SoBitmapFontCache.cpp \
           database/src/so/caches/SoBoundingBoxCache.cpp \
           database/src/so/caches/SoCache.cpp \
           database/src/so/caches/SoGLCacheList.cpp \
           database/src/so/caches/SoGLRenderCache.cpp \
           database/src/so/caches/SoNormalCache.cpp \
           database/src/so/caches/SoVertexPropertyCache.cpp \
           database/src/so/details/SoConeDetail.cpp \
           database/src/so/details/SoCubeDetail.cpp \
           database/src/so/details/SoCylinderDetail.cpp \
           database/src/so/details/SoDetail.cpp \
           database/src/so/details/SoDetailInit.cpp \
           database/src/so/details/SoFaceDetail.cpp \
           database/src/so/details/SoLineDetail.cpp \
           database/src/so/details/SoPointDetail.cpp \
           database/src/so/details/SoTextDetail.cpp \
           database/src/so/elements/SoAccumulatedElement.cpp \
           database/src/so/elements/SoBBoxModelMatrixElement.cpp \
           database/src/so/elements/SoCacheElement.cpp \
           database/src/so/elements/SoClipPlaneElement.cpp \
           database/src/so/elements/SoComplexityElement.cpp \
           database/src/so/elements/SoComplexityTypeElement.cpp \
           database/src/so/elements/SoCoordinateElement.cpp \
           database/src/so/elements/SoCreaseAngleElement.cpp \
           database/src/so/elements/SoDrawStyleElement.cpp \
           database/src/so/elements/SoElement.cpp \
           database/src/so/elements/SoElementInit.cpp \
           database/src/so/elements/SoFloatElement.cpp \
           database/src/so/elements/SoFocalDistanceElement.cpp \
           database/src/so/elements/SoFontNameElement.cpp \
           database/src/so/elements/SoFontSizeElement.cpp \
           database/src/so/elements/SoGLCacheContextElement.cpp \
           database/src/so/elements/SoGLClipPlaneElement.cpp \
           database/src/so/elements/SoGLCoordinateElement.cpp \
           database/src/so/elements/SoGLDrawStyleElement.cpp \
           database/src/so/elements/SoGLLazyElement.cpp \
           database/src/so/elements/SoGLLightIdElement.cpp \
           database/src/so/elements/SoGLLinePatternElement.cpp \
           database/src/so/elements/SoGLLineWidthElement.cpp \
           database/src/so/elements/SoGLModelMatrixElement.cpp \
           database/src/so/elements/SoGLNormalElement.cpp \
           database/src/so/elements/SoGLPointSizeElement.cpp \
           database/src/so/elements/SoGLProjectionMatrixElement.cpp \
           database/src/so/elements/SoGLRenderPassElement.cpp \
           database/src/so/elements/SoGLShapeHintsElement.cpp \
           database/src/so/elements/SoGLTextureCoordinateElement.cpp \
           database/src/so/elements/SoGLTextureEnabledElement.cpp \
           database/src/so/elements/SoGLTextureImageElement.cpp \
           database/src/so/elements/SoGLTextureMatrixElement.cpp \
           database/src/so/elements/SoGLUpdateAreaElement.cpp \
           database/src/so/elements/SoGLViewingMatrixElement.cpp \
           database/src/so/elements/SoGLViewportRegionElement.cpp \
           database/src/so/elements/SoInt32Element.cpp \
           database/src/so/elements/SoLazyElement.cpp \
           database/src/so/elements/SoLightAttenuationElement.cpp \
           database/src/so/elements/SoLinePatternElement.cpp \
           database/src/so/elements/SoLineWidthElement.cpp \
           database/src/so/elements/SoLocalBBoxMatrixElement.cpp \
           database/src/so/elements/SoMaterialBindingElement.cpp \
           database/src/so/elements/SoModelMatrixElement.cpp \
           database/src/so/elements/SoNormalBindingElement.cpp \
           database/src/so/elements/SoNormalElement.cpp \
           database/src/so/elements/SoOverrideElement.cpp \
           database/src/so/elements/SoPickRayElement.cpp \
           database/src/so/elements/SoPickStyleElement.cpp \
           database/src/so/elements/SoPointSizeElement.cpp \
           database/src/so/elements/SoProfileCoordinateElement.cpp \
           database/src/so/elements/SoProfileElement.cpp \
           database/src/so/elements/SoProjectionMatrixElement.cpp \
           database/src/so/elements/SoReplacedElement.cpp \
           database/src/so/elements/SoShapeHintsElement.cpp \
           database/src/so/elements/SoShapeStyleElement.cpp \
           database/src/so/elements/SoSwitchElement.cpp \
           database/src/so/elements/SoTextureCoordinateBindingElement.cpp \
           database/src/so/elements/SoTextureCoordinateElement.cpp \
           database/src/so/elements/SoTextureImageElement.cpp \
           database/src/so/elements/SoTextureMatrixElement.cpp \
           database/src/so/elements/SoTextureQualityElement.cpp \
           database/src/so/elements/SoUnitsElement.cpp \
           database/src/so/elements/SoViewingMatrixElement.cpp \
           database/src/so/elements/SoViewportRegionElement.cpp \
           database/src/so/elements/SoViewVolumeElement.cpp \
           database/src/so/elements/SoWindowElement.cpp \
           database/src/so/engines/SoBoolOperation.cpp \
           database/src/so/engines/SoCalcExpr.cpp \
           database/src/so/engines/SoCalcParse.cpp \
           database/src/so/engines/SoCalculator.cpp \
           database/src/so/engines/SoCompose.cpp \
           database/src/so/engines/SoComputeBoundingBox.cpp \
           database/src/so/engines/SoConcatenate.cpp \
           database/src/so/engines/SoCounter.cpp \
           database/src/so/engines/SoElapsedTime.cpp \
           database/src/so/engines/SoEngine.cpp \
           database/src/so/engines/SoEngineInit.cpp \
           database/src/so/engines/SoFieldConverter.cpp \
           database/src/so/engines/SoFieldConverters.cpp \
           database/src/so/engines/SoGate.cpp \
           database/src/so/engines/SoInterpolate.cpp \
           database/src/so/engines/SoOneShot.cpp \
           database/src/so/engines/SoOnOff.cpp \
           database/src/so/engines/SoOutputData.cpp \
           database/src/so/engines/SoSelectOne.cpp \
           database/src/so/engines/SoTimeCounter.cpp \
           database/src/so/engines/SoTransformVec3f.cpp \
           database/src/so/engines/SoTriggerAny.cpp \
           database/src/so/engines/SoUnknownEngine.cpp \
           database/src/so/errors/SoDebugError.cpp \
           database/src/so/errors/SoError.cpp \
           database/src/so/errors/SoErrorInit.cpp \
           database/src/so/errors/SoMemoryError.cpp \
           database/src/so/errors/SoReadError.cpp \
           database/src/so/events/SoButtonEvent.cpp \
           database/src/so/events/SoEvent.cpp \
           database/src/so/events/SoEventInit.cpp \
           database/src/so/events/SoKeyboardEvent.cpp \
           database/src/so/events/SoLocation2Event.cpp \
           database/src/so/events/SoMotion3Event.cpp \
           database/src/so/events/SoMouseButtonEvent.cpp \
           database/src/so/events/SoSpaceballButtonEvent.cpp \
           database/src/so/fields/SoField.cpp \
           database/src/so/fields/SoSField.cpp \
           database/src/so/fields/SoMField.cpp \
           database/src/so/fields/SoFieldContainer.cpp \
           database/src/so/fields/SoFieldData.cpp \
           database/src/so/fields/SoFieldInit.cpp \
           database/src/so/fields/SoGlobalField.cpp \
           database/src/so/fields/SoMFBitMask.cpp \
           database/src/so/fields/SoMFBool.cpp \
           database/src/so/fields/SoMFColor.cpp \
           database/src/so/fields/SoMFEngine.cpp \
           database/src/so/fields/SoMFEnum.cpp \
           database/src/so/fields/SoMFFloat.cpp \
           database/src/so/fields/SoMFInt32.cpp \
           database/src/so/fields/SoMFMatrix.cpp \
           database/src/so/fields/SoMFName.cpp \
           database/src/so/fields/SoMFNode.cpp \
           database/src/so/fields/SoMFPath.cpp \
           database/src/so/fields/SoMFPlane.cpp \
           database/src/so/fields/SoMFRotation.cpp \
           database/src/so/fields/SoMFShort.cpp \
           database/src/so/fields/SoMFString.cpp \
           database/src/so/fields/SoMFTime.cpp \
           database/src/so/fields/SoMFUInt32.cpp \
           database/src/so/fields/SoMFUShort.cpp \
           database/src/so/fields/SoMFVec2f.cpp \
           database/src/so/fields/SoMFVec3f.cpp \
           database/src/so/fields/SoMFVec4f.cpp \
           database/src/so/fields/SoSFBitMask.cpp \
           database/src/so/fields/SoSFBool.cpp \
           database/src/so/fields/SoSFBox3f.cpp \
           database/src/so/fields/SoSFColor.cpp \
           database/src/so/fields/SoSFEngine.cpp \
           database/src/so/fields/SoSFEnum.cpp \
           database/src/so/fields/SoSFFloat.cpp \
           database/src/so/fields/SoSFImage.cpp \
           database/src/so/fields/SoSFInt32.cpp \
           database/src/so/fields/SoSFMatrix.cpp \
           database/src/so/fields/SoSFName.cpp \
           database/src/so/fields/SoSFNode.cpp \
           database/src/so/fields/SoSFPath.cpp \
           database/src/so/fields/SoSFPlane.cpp \
           database/src/so/fields/SoSFRotation.cpp \
           database/src/so/fields/SoSFShort.cpp \
           database/src/so/fields/SoSFString.cpp \
           database/src/so/fields/SoSFTime.cpp \
           database/src/so/fields/SoSFTrigger.cpp \
           database/src/so/fields/SoSFUInt32.cpp \
           database/src/so/fields/SoSFUShort.cpp \
           database/src/so/fields/SoSFVec2f.cpp \
           database/src/so/fields/SoSFVec3f.cpp \
           database/src/so/fields/SoSFVec4f.cpp \
           database/src/so/nodes/SoAnnotation.cpp \
           database/src/so/nodes/SoArray.cpp \
           database/src/so/nodes/SoAsciiText.cpp \
           database/src/so/nodes/SoBaseColor.cpp \
           database/src/so/nodes/SoBlinker.cpp \
           database/src/so/nodes/SoCallback.cpp \
           database/src/so/nodes/SoCamera.cpp \
           database/src/so/nodes/SoClipPlane.cpp \
           database/src/so/nodes/SoColorIndex.cpp \
           database/src/so/nodes/SoComplexity.cpp \
           database/src/so/nodes/SoCone.cpp \
           database/src/so/nodes/SoCoordinate3.cpp \
           database/src/so/nodes/SoCoordinate4.cpp \
           database/src/so/nodes/SoCube.cpp \
           database/src/so/nodes/SoCylinder.cpp \
           database/src/so/nodes/SoDirectionalLight.cpp \
           database/src/so/nodes/SoDrawStyle.cpp \
           database/src/so/nodes/SoEnvironment.cpp \
           database/src/so/nodes/SoEventCallback.cpp \
           database/src/so/nodes/SoFaceSet.cpp \
           database/src/so/nodes/SoFile.cpp \
           database/src/so/nodes/SoFont.cpp \
           database/src/so/nodes/SoFontStyle.cpp \
           database/src/so/nodes/SoGroup.cpp \
           database/src/so/nodes/SoIndexedFaceSet.cpp \
           database/src/so/nodes/SoIndexedLineSet.cpp \
           database/src/so/nodes/SoIndexedNurbsCurve.cpp \
           database/src/so/nodes/SoIndexedNurbsSurface.cpp \
           database/src/so/nodes/SoIndexedShape.cpp \
           database/src/so/nodes/SoIndexedTriangleStripSet.cpp \
           database/src/so/nodes/SoInfo.cpp \
           database/src/so/nodes/SoLabel.cpp \
           database/src/so/nodes/SoLevelOfDetail.cpp \
           database/src/so/nodes/SoLight.cpp \
           database/src/so/nodes/SoLightModel.cpp \
           database/src/so/nodes/SoLinearProfile.cpp \
           database/src/so/nodes/SoLineSet.cpp \
           database/src/so/nodes/SoLocateHighlight.cpp \
           database/src/so/nodes/SoLOD.cpp \
           database/src/so/nodes/SoMaterial.cpp \
           database/src/so/nodes/SoMaterialBinding.cpp \
           database/src/so/nodes/SoMatrixTransform.cpp \
           database/src/so/nodes/SoMultipleCopy.cpp \
           database/src/so/nodes/SoNode.cpp \
           database/src/so/nodes/SoNodeInit.cpp \
           database/src/so/nodes/SoNonIndexedShape.cpp \
           database/src/so/nodes/SoNormal.cpp \
           database/src/so/nodes/SoNormalBinding.cpp \
           database/src/so/nodes/SoNurbsCurve.cpp \
           database/src/so/nodes/SoNurbsProfile.cpp \
           database/src/so/nodes/SoNurbsSurface.cpp \
           database/src/so/nodes/SoOrthographicCamera.cpp \
           database/src/so/nodes/SoPackedColor.cpp \
           database/src/so/nodes/SoPathSwitch.cpp \
           database/src/so/nodes/SoPendulum.cpp \
           database/src/so/nodes/SoPerspectiveCamera.cpp \
           database/src/so/nodes/SoPickStyle.cpp \
           database/src/so/nodes/SoPointLight.cpp \
           database/src/so/nodes/SoPointSet.cpp \
           database/src/so/nodes/SoProfile.cpp \
           database/src/so/nodes/SoProfileCoordinate2.cpp \
           database/src/so/nodes/SoProfileCoordinate3.cpp \
           database/src/so/nodes/SoQuadMesh.cpp \
           database/src/so/nodes/SoResetTransform.cpp \
           database/src/so/nodes/SoRotation.cpp \
           database/src/so/nodes/SoRotationXYZ.cpp \
           database/src/so/nodes/SoRotor.cpp \
           database/src/so/nodes/SoScale.cpp \
           database/src/so/nodes/SoSeparator.cpp \
           database/src/so/nodes/SoShape.cpp \
           database/src/so/nodes/SoShapeHints.cpp \
           database/src/so/nodes/SoShuttle.cpp \
           database/src/so/nodes/SoSphere.cpp \
           database/src/so/nodes/SoSpotLight.cpp \
           database/src/so/nodes/SoSwitch.cpp \
           database/src/so/nodes/SoText2.cpp \
           database/src/so/nodes/SoText3.cpp \
           database/src/so/nodes/SoTexture2.cpp \
           database/src/so/nodes/SoTexture2Transform.cpp \
           database/src/so/nodes/SoTextureCoordinate2.cpp \
           database/src/so/nodes/SoTextureCoordinateBinding.cpp \
           database/src/so/nodes/SoTextureCoordinateDefault.cpp \
           database/src/so/nodes/SoTextureCoordinateEnvironment.cpp \
           database/src/so/nodes/SoTextureCoordinateFunction.cpp \
           database/src/so/nodes/SoTextureCoordinatePlane.cpp \
           database/src/so/nodes/SoTransform.cpp \
           database/src/so/nodes/SoTransformation.cpp \
           database/src/so/nodes/SoTransformSeparator.cpp \
           database/src/so/nodes/SoTranslation.cpp \
           database/src/so/nodes/SoTriangleStripSet.cpp \
           database/src/so/nodes/SoUnits.cpp \
           database/src/so/nodes/SoUnknownNode.cpp \
           database/src/so/nodes/SoVertexProperty.cpp \
           database/src/so/nodes/SoVertexShape.cpp \
           database/src/so/nodes/SoWWWAnchor.cpp \
           database/src/so/nodes/SoWWWInline.cpp \
           database/src/so/sensors/SoAlarmSensor.cpp \
           database/src/so/sensors/SoDataSensor.cpp \
           database/src/so/sensors/SoDelayQueueSensor.cpp \
           database/src/so/sensors/SoFieldSensor.cpp \
           database/src/so/sensors/SoIdleSensor.cpp \
           database/src/so/sensors/SoNodeSensor.cpp \
           database/src/so/sensors/SoOneShotSensor.cpp \
           database/src/so/sensors/SoPathSensor.cpp \
           database/src/so/sensors/SoSensor.cpp \
           database/src/so/sensors/SoSensorMgr.cpp \
           database/src/so/sensors/SoTimerQueueSensor.cpp \
           database/src/so/sensors/SoTimerSensor.cpp \
           database/src/so/upgraders/SoUpgrader.cpp \
           database/src/so/upgraders/SoUpgraderInit.cpp \
           database/src/so/upgraders/SoV1CustomNode.cpp \
           database/src/so/upgraders/SoV1DrawStyle.cpp \
           database/src/so/upgraders/SoV1Environment.cpp \
           database/src/so/upgraders/SoV1IndexedTriangleMesh.cpp \
           database/src/so/upgraders/SoV1LayerGroup.cpp \
           database/src/so/upgraders/SoV1LightModel.cpp \
           database/src/so/upgraders/SoV1Material.cpp \
           database/src/so/upgraders/SoV1PackedColor.cpp \
           database/src/so/upgraders/SoV1PickStyle.cpp \
           database/src/so/upgraders/SoV1Separator.cpp \
           database/src/so/upgraders/SoV1ShapeHints.cpp \
           database/src/so/upgraders/SoV1Text2.cpp \
           database/src/so/upgraders/SoV1Text3.cpp \
           database/src/so/upgraders/SoV1Texture2.cpp \
           database/src/so/upgraders/SoV1TextureCoordinateCube.cpp \
           database/src/so/upgraders/SoV1TextureCoordinateCylinder.cpp \
           database/src/so/upgraders/SoV1TextureCoordinateEnvironment.cpp \
           database/src/so/upgraders/SoV1TextureCoordinatePlane.cpp \
           database/src/so/upgraders/SoV1TextureCoordinateSphere.cpp \
           database/src/so/upgraders/SoV2AsciiText.cpp \
           database/src/so/upgraders/SoV2FontStyle.cpp \
           database/src/so/upgraders/SoV2LOD.cpp \
           database/src/so/upgraders/SoV2MaterialIndex.cpp \
           database/src/so/upgraders/SoV2Text2.cpp \
           database/src/so/upgraders/SoV2Text3.cpp \
           database/src/so/upgraders/SoV2VertexProperty.cpp \
           database/src/so/upgraders/SoV2WWWAnchor.cpp \
           database/src/so/upgraders/SoV2WWWInline.cpp \
           database/src/so/nodes/nurbs/SoCurveMaps.cpp \
           database/src/so/nodes/nurbs/SoCurveRender.cpp \
           database/src/so/nodes/nurbs/SoCurveRndEvl.cpp \
           database/src/so/nodes/nurbs/SoGLRender.cpp \
           database/src/so/nodes/nurbs/SoPickEvals.cpp \
           database/src/so/nodes/nurbs/SoPickMaps.cpp \
           database/src/so/nodes/nurbs/SoPickRender.cpp \
           database/src/so/nodes/nurbs/SoPrimEvals.cpp \
           database/src/so/nodes/nurbs/SoPrimMaps.cpp \
           database/src/so/nodes/nurbs/SoPrimRender.cpp \
           database/src/so/nodes/nurbs/clients/nurbsClient.cpp \
           database/src/so/nodes/nurbs/libnurbs/libNurbs.cpp
