######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:54:41 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ivperf.cpp
