######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:55:20 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GeneralizedCylinder.h NurbMaker.h Triangulator.h
SOURCES += GeneralizedCylinder.cpp NurbMaker.cpp Triangulator.cpp
