######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 22:08:05 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += box.h mazes.h PlayClass.h
SOURCES += maze.cpp PlayClass.cpp
