######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:54:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ivAddVP.cpp
