######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 22:05:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 4view.cpp
