######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:55:04 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ivviewMenus.h
SOURCES += ivview.cpp
