######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 23 21:55:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../../lib/database/include/

# Input
HEADERS += BarChart.h
SOURCES += BarChart.cpp
